const fs = require("fs");
const path = require("path");

const csvPath = path.resolve("exports", "李敖语录_诗文格言歌谣引用.csv");
const reportPath = path.resolve("analysis", "liao_liao_yulu_proofread_report.txt");

const columns = [
  "id",
  "book",
  "chapter",
  "source_file",
  "line_start",
  "line_end",
  "quote_text",
  "category",
  "source_or_origin",
  "summary",
  "notes",
];

function parseCsv(text) {
  const rows = [];
  let row = [];
  let value = "";
  let inQuotes = false;
  const cleanText = text.replace(/^\uFEFF/, "");

  for (let index = 0; index < cleanText.length; index += 1) {
    const char = cleanText[index];
    const next = cleanText[index + 1];

    if (inQuotes) {
      if (char === '"' && next === '"') {
        value += '"';
        index += 1;
      } else if (char === '"') {
        inQuotes = false;
      } else {
        value += char;
      }
      continue;
    }

    if (char === '"') {
      inQuotes = true;
    } else if (char === ",") {
      row.push(value);
      value = "";
    } else if (char === "\n") {
      row.push(value.replace(/\r$/, ""));
      rows.push(row);
      row = [];
      value = "";
    } else {
      value += char;
    }
  }

  if (value.length > 0 || row.length > 0) {
    row.push(value.replace(/\r$/, ""));
    rows.push(row);
  }

  const header = rows.shift().map((name) => name.replace(/^\uFEFF/, ""));
  return rows
    .filter((cells) => cells.some((cell) => cell !== ""))
    .map((cells) =>
      Object.fromEntries(header.map((name, index) => [name, cells[index] ?? ""])),
    );
}

const csvEscape = (value) => `"${String(value ?? "").replace(/"/g, '""')}"`;

function stringifyCsv(rows) {
  return [
    columns.join(","),
    ...rows.map((row) => columns.map((column) => csvEscape(row[column])).join(",")),
  ].join("\n") + "\n";
}

const removed = new Map([
  [
    "LALAYL-154",
    "塞万提斯相关语只是转述为“间不容针”的短碎片，独立性太弱，校对轮剔除。",
  ],
]);

const additions = [
  {
    id: "LALAYL-156",
    book: "李敖语录",
    chapter: "自我炼钢",
    source_file: "004.自我炼钢.txt",
    line_start: "43",
    line_end: "43",
    quote_text:
      "普通的生活是感觉的生活（life of senses），是属于声色香味的生活，而不是意志的生活（life of Will）。意志的生活是另一种境界，只有特立独行的人才能过得了的。",
    category: "人生格言",
    source_or_origin: "原书引述，未标明来源",
    summary: "李敖引用“感觉的生活”与“意志的生活”之辨来说明自我锻炼。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-157",
    book: "李敖语录",
    chapter: "自我炼钢",
    source_file: "004.自我炼钢.txt",
    line_start: "47",
    line_end: "47",
    quote_text: "起来！这是你自己应该办的事，我们也赞助你，鼓起勇气去干！",
    category: "宗教经典译句",
    source_or_origin: "《以斯拉记》10:4 中文译意，原书随引",
    summary: "李敖在引用 Ezra 10:4 英文后附中文译意，用作道德勇气的颂词。",
    notes: "校对轮补入；与原英文条目互补。",
  },
  {
    id: "LALAYL-158",
    book: "李敖语录",
    chapter: "中国历史人物",
    source_file: "008.中国历史人物.txt",
    line_start: "29",
    line_end: "29",
    quote_text: "入太庙，每事问",
    category: "古典文句",
    source_or_origin: "《论语·八佾》语，原书引述",
    summary: "李敖引用孔子入太庙每事问，说明孔子的学生气质。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-159",
    book: "李敖语录",
    chapter: "中国历史人物",
    source_file: "008.中国历史人物.txt",
    line_start: "29",
    line_end: "29",
    quote_text: "三人行，必有我师",
    category: "古典文句",
    source_or_origin: "《论语·述而》语，原书引述",
    summary: "李敖引用《论语》名句说明孔子从宽录取老师的标准。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-160",
    book: "李敖语录",
    chapter: "中国历史人物",
    source_file: "008.中国历史人物.txt",
    line_start: "29",
    line_end: "29",
    quote_text: "不耻下问",
    category: "古典成句",
    source_or_origin: "《论语·公冶长》成句，原书引述",
    summary: "李敖引用“不耻下问”说明孔子的学习姿态。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-161",
    book: "李敖语录",
    chapter: "中国历史人物",
    source_file: "008.中国历史人物.txt",
    line_start: "31",
    line_end: "31",
    quote_text: "当仁不让于师",
    category: "古典文句",
    source_or_origin: "《论语·卫灵公》语，原书引述",
    summary: "李敖引用《论语》说明在真理面前不因老师而退让。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-162",
    book: "李敖语录",
    chapter: "中国历史人物",
    source_file: "008.中国历史人物.txt",
    line_start: "49",
    line_end: "49",
    quote_text: "一箪食、一瓢饮",
    category: "古典文句",
    source_or_origin: "《论语·雍也》语，原书引述",
    summary: "李敖引用颜回“一箪食、一瓢饮”的生活来批评苦行化标准。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-163",
    book: "李敖语录",
    chapter: "中国历史人物",
    source_file: "008.中国历史人物.txt",
    line_start: "61",
    line_end: "61",
    quote_text: "墨子兼爱，摩顶放踵，利天下为之",
    category: "古典文句",
    source_or_origin: "《孟子》论墨子语，原书引述",
    summary: "李敖引用孟子对墨子兼爱精神的概括。",
    notes: "校对轮补入；古典思想句。",
  },
  {
    id: "LALAYL-164",
    book: "李敖语录",
    chapter: "中国历史人物",
    source_file: "008.中国历史人物.txt",
    line_start: "61",
    line_end: "61",
    quote_text: "赴火蹈刃，死不旋踵",
    category: "古典成句",
    source_or_origin: "古典文句，原书引述墨家作风",
    summary: "李敖引用“赴火蹈刃，死不旋踵”说明墨家苦行与勇决。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-165",
    book: "李敖语录",
    chapter: "中国历史人物",
    source_file: "008.中国历史人物.txt",
    line_start: "81",
    line_end: "81",
    quote_text: "若非吾故人乎？",
    category: "古典史传文句",
    source_or_origin: "《史记·项羽本纪》语，原书引述",
    summary: "李敖引用项羽乌江对故人吕马童之语。",
    notes: "校对轮补入；古典史传语。",
  },
  {
    id: "LALAYL-166",
    book: "李敖语录",
    chapter: "中国历史人物",
    source_file: "008.中国历史人物.txt",
    line_start: "81",
    line_end: "81",
    quote_text: "吾闻汉购我头：千金，邑万户。吾为若德。",
    category: "古典史传文句",
    source_or_origin: "《史记·项羽本纪》语，原书引述",
    summary: "李敖引用项羽以头赠故人的史传句，说明英雄末路的风范。",
    notes: "校对轮补入；古典史传语。",
  },
  {
    id: "LALAYL-167",
    book: "李敖语录",
    chapter: "人生拾零",
    source_file: "011.人生拾零.txt",
    line_start: "49",
    line_end: "49",
    quote_text: "卒然临之而不惊，无故加之而不怒",
    category: "古典文句",
    source_or_origin: "苏轼《留侯论》句，原书引述",
    summary: "李敖引用苏轼《留侯论》说明第一流人的从容。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-168",
    book: "李敖语录",
    chapter: "人生拾零",
    source_file: "011.人生拾零.txt",
    line_start: "49",
    line_end: "49",
    quote_text: "所挟持者甚大，而其志甚远也",
    category: "古典文句",
    source_or_origin: "苏轼《留侯论》句，原书引述",
    summary: "李敖引用苏轼《留侯论》说明第一流人的志趣高迈。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-169",
    book: "李敖语录",
    chapter: "人生拾零",
    source_file: "011.人生拾零.txt",
    line_start: "75",
    line_end: "75",
    quote_text: "你是从土而出的，你本是尘土，仍要归于尘土。",
    category: "宗教经典译句",
    source_or_origin: "《创世记》3:19 语意，原书明注圣经",
    summary: "李敖引用圣经尘土归尘土之语，谈人与自然循环。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-170",
    book: "李敖语录",
    chapter: "人生拾零",
    source_file: "011.人生拾零.txt",
    line_start: "101",
    line_end: "101",
    quote_text: "本不植高原，今日复何悔",
    category: "古典诗句",
    source_or_origin: "古典诗句，原书引述",
    summary: "李敖引用诗句说明意志力中的浩然胸怀。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-171",
    book: "李敖语录",
    chapter: "人生拾零",
    source_file: "011.人生拾零.txt",
    line_start: "105",
    line_end: "105",
    quote_text: "羽扇纶巾，谈笑间，强虏灰飞烟灭",
    category: "古典诗句",
    source_or_origin: "苏轼《念奴娇·赤壁怀古》句，原书明注",
    summary: "李敖引用苏轼词句写从容风度。",
    notes: "校对轮补入；文学引用。",
  },
  {
    id: "LALAYL-172",
    book: "李敖语录",
    chapter: "人生拾零",
    source_file: "011.人生拾零.txt",
    line_start: "177",
    line_end: "177",
    quote_text: "莫如半日静坐，半日读书",
    category: "古典格言",
    source_or_origin: "朱熹式修身语，原书引述",
    summary: "李敖引用古人静坐读书标准来批评枯燥的正统娱乐观。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-173",
    book: "李敖语录",
    chapter: "人生拾零",
    source_file: "011.人生拾零.txt",
    line_start: "191",
    line_end: "191",
    quote_text: "祸兮福之所倚；福兮祸之所伏",
    category: "古典格言",
    source_or_origin: "《老子》语，原书引述",
    summary: "李敖引用老子祸福相依之语说明顺逆转换。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-174",
    book: "李敖语录",
    chapter: "敌人与朋友",
    source_file: "012.敌人与朋友.txt",
    line_start: "15",
    line_end: "15",
    quote_text: "东飞伯劳西飞燕",
    category: "古典诗句",
    source_or_origin: "古乐府成句，原书引述",
    summary: "李敖引用“东飞伯劳西飞燕”写旧友星散。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-175",
    book: "李敖语录",
    chapter: "天南地北",
    source_file: "013.天南地北.txt",
    line_start: "99",
    line_end: "99",
    quote_text: "风林灯火观书夜",
    category: "古典诗句",
    source_or_origin: "古典诗句，原书引述",
    summary: "李敖引用写蝉声与读书夜的诗句。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-176",
    book: "李敖语录",
    chapter: "天南地北",
    source_file: "013.天南地北.txt",
    line_start: "99",
    line_end: "99",
    quote_text: "十万蝉声作雨凉",
    category: "古典诗句",
    source_or_origin: "古典诗句，原书引述",
    summary: "李敖引用写蝉声成雨凉的诗句。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-177",
    book: "李敖语录",
    chapter: "天南地北",
    source_file: "013.天南地北.txt",
    line_start: "191",
    line_end: "191",
    quote_text: "纸上罗曼斯",
    category: "外国文学语",
    source_or_origin: "萧伯纳语，原书明注",
    summary: "李敖引用萧伯纳“纸上罗曼斯”谈情书。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-178",
    book: "李敖语录",
    chapter: "谈西说东",
    source_file: "014.谈西说东.txt",
    line_start: "7",
    line_end: "7",
    quote_text: "何以报德",
    category: "古典文句",
    source_or_origin: "《论语·宪问》语，原书引述",
    summary: "李敖引用孔子反问“何以报德”来谈以德报怨。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-179",
    book: "李敖语录",
    chapter: "谈西说东",
    source_file: "014.谈西说东.txt",
    line_start: "17",
    line_end: "17",
    quote_text: "君子诛意不诛事",
    category: "古典成句",
    source_or_origin: "春秋笔法成句，原书引述",
    summary: "李敖引用“君子诛意不诛事”批评只问动机不问事实。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-180",
    book: "李敖语录",
    chapter: "谈西说东",
    source_file: "014.谈西说东.txt",
    line_start: "35",
    line_end: "35",
    quote_text: "未明出世旨，宁歇累生狂",
    category: "古典诗句",
    source_or_origin: "古典诗句，原书引述",
    summary: "李敖引用古诗句表达少发空论、实践为先。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-181",
    book: "李敖语录",
    chapter: "谈西说东",
    source_file: "014.谈西说东.txt",
    line_start: "105",
    line_end: "105",
    quote_text: "老僧为百万生灵，何惜如来一戒！",
    category: "佛教轶事语",
    source_or_origin: "破山和尚轶事语，原书引述",
    summary: "李敖引用破山和尚破戒救人的故事说明佛法破执。",
    notes: "校对轮补入；宗教轶事语。",
  },
  {
    id: "LALAYL-182",
    book: "李敖语录",
    chapter: "谈西说东",
    source_file: "014.谈西说东.txt",
    line_start: "127",
    line_end: "127",
    quote_text: "朱门酒肉臭，路有冻死骨，荣枯咫尺异，惆怅难再述",
    category: "古典诗句",
    source_or_origin: "杜甫《自京赴奉先县咏怀五百字》句，原书引述",
    summary: "李敖引用杜甫诗句谈短暂同情与社会冷暖。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-183",
    book: "李敖语录",
    chapter: "谈西说东",
    source_file: "014.谈西说东.txt",
    line_start: "143",
    line_end: "143",
    quote_text: "设想英雄垂暮日，温柔不住住何乡？",
    category: "古典诗句",
    source_or_origin: "龚自珍诗句，原书明注",
    summary: "李敖引用龚自珍诗句谈英雄垂暮与温柔。",
    notes: "校对轮补入；文学引用。",
  },
  {
    id: "LALAYL-184",
    book: "李敖语录",
    chapter: "谈西说东",
    source_file: "014.谈西说东.txt",
    line_start: "175",
    line_end: "175",
    quote_text: "丈夫啸闻百里，妇人啸闻五十里。如笙竽之音",
    category: "古典文句",
    source_or_origin: "《拾遗记》语，原书明注",
    summary: "李敖引用《拾遗记》里善啸之国的描述。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-185",
    book: "李敖语录",
    chapter: "谈西说东",
    source_file: "014.谈西说东.txt",
    line_start: "221",
    line_end: "221",
    quote_text: "福无双至，祸不单行。",
    category: "传统俗语",
    source_or_origin: "俗话，原书明注",
    summary: "李敖引用俗话引出化祸为福的讨论。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-186",
    book: "李敖语录",
    chapter: "谈西说东",
    source_file: "014.谈西说东.txt",
    line_start: "221",
    line_end: "221",
    quote_text: "人生不如意事，常十之八九",
    category: "传统俗语",
    source_or_origin: "传统俗语，原书引述",
    summary: "李敖引用俗语说明不如意事在人生中的常态。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-187",
    book: "李敖语录",
    chapter: "批评中国知识分子",
    source_file: "017.批评中国知识分子.txt",
    line_start: "31",
    line_end: "31",
    quote_text: "忍把浮名，换作浅斟低唱",
    category: "古典词句",
    source_or_origin: "柳永《鹤冲天》句，原书引述",
    summary: "李敖引用柳永词句说明旧式知识分子的退隐风流。",
    notes: "校对轮补入；文学引用。",
  },
  {
    id: "LALAYL-188",
    book: "李敖语录",
    chapter: "批评中国知识分子",
    source_file: "017.批评中国知识分子.txt",
    line_start: "159",
    line_end: "159",
    quote_text: "没有人属于一个岛",
    category: "外国诗文译句",
    source_or_origin: "约翰·邓恩诗文名句译意，原书引述",
    summary: "李敖引用约翰·邓恩名句说明宽广眼界。",
    notes: "校对轮补入；文学引用。",
  },
  {
    id: "LALAYL-189",
    book: "李敖语录",
    chapter: "论中西文化",
    source_file: "018.论中西文化.txt",
    line_start: "63",
    line_end: "63",
    quote_text: "还君明珠双泪垂",
    category: "古典诗句",
    source_or_origin: "张籍《节妇吟》句，原书引述",
    summary: "李敖引用张籍诗句说明面对西方文化时不能“还珠”。",
    notes: "校对轮补入；文学引用。",
  },
  {
    id: "LALAYL-190",
    book: "李敖语录",
    chapter: "历史探索",
    source_file: "019.历史探索.txt",
    line_start: "69",
    line_end: "69",
    quote_text: "若想人不知，除非己莫为",
    category: "传统俗语",
    source_or_origin: "传统俗语，原书引述",
    summary: "李敖引用俗语说明历史直笔终会留下真相。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-191",
    book: "李敖语录",
    chapter: "批判中国传统",
    source_file: "020.批判中国传统.txt",
    line_start: "93",
    line_end: "93",
    quote_text: "割不正，不食",
    category: "古典文句",
    source_or_origin: "《论语·乡党》语，原书引述",
    summary: "李敖引用《论语》饮食礼句来批评传统把娱乐饮食道德化。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-192",
    book: "李敖语录",
    chapter: "批判中国传统",
    source_file: "020.批判中国传统.txt",
    line_start: "101",
    line_end: "101",
    quote_text: "吾闻君子不博",
    category: "古典文句",
    source_or_origin: "《孔子家语》语，原书引述",
    summary: "李敖引用“吾闻君子不博”说明古书中的赌博观。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-193",
    book: "李敖语录",
    chapter: "批判中国传统",
    source_file: "020.批判中国传统.txt",
    line_start: "129",
    line_end: "129",
    quote_text: "人所坐卧曰床。床，装也，所以自装载也。",
    category: "古典训诂文句",
    source_or_origin: "古代训诂语，原书引述",
    summary: "李敖引用古人对“床”的定义说明古代床的概念。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-194",
    book: "李敖语录",
    chapter: "批判中国传统",
    source_file: "020.批判中国传统.txt",
    line_start: "135",
    line_end: "135",
    quote_text: "子非吾友也",
    category: "古典轶事语",
    source_or_origin: "管宁割席故事语，原书引述",
    summary: "李敖引用管宁割席之语说明同席规矩。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-195",
    book: "李敖语录",
    chapter: "批判中国传统",
    source_file: "020.批判中国传统.txt",
    line_start: "171",
    line_end: "171",
    quote_text: "男女授受不亲",
    category: "古典礼教成句",
    source_or_origin: "传统礼教成句，原书引述",
    summary: "李敖引用传统礼教成句说明中国婚恋观。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-196",
    book: "李敖语录",
    chapter: "批判中国传统",
    source_file: "020.批判中国传统.txt",
    line_start: "171",
    line_end: "171",
    quote_text: "男女不杂坐",
    category: "古典礼教成句",
    source_or_origin: "传统礼教成句，原书引述",
    summary: "李敖引用传统礼教成句说明中国婚恋观。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-197",
    book: "李敖语录",
    chapter: "批判中国传统",
    source_file: "020.批判中国传统.txt",
    line_start: "171",
    line_end: "171",
    quote_text: "无媒不交，无币不相见",
    category: "古典礼教成句",
    source_or_origin: "传统礼教成句，原书引述",
    summary: "李敖引用传统礼教成句说明古代婚恋风俗。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-198",
    book: "李敖语录",
    chapter: "批判中国传统",
    source_file: "020.批判中国传统.txt",
    line_start: "173",
    line_end: "173",
    quote_text: "以礼自防",
    category: "古典礼教成句",
    source_or_origin: "传统礼教成句，原书引述",
    summary: "李敖引用“以礼自防”说明传统礼教限制真感情。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-199",
    book: "李敖语录",
    chapter: "批判中国传统",
    source_file: "020.批判中国传统.txt",
    line_start: "383",
    line_end: "383",
    quote_text: "酒色财气，不碍菩提路",
    category: "佛教成句",
    source_or_origin: "禅宗式成句，原书引述",
    summary: "李敖引用禅宗式成句说明不守清规的自然与快意。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-200",
    book: "李敖语录",
    chapter: "论中国文学",
    source_file: "021.论中国文学.txt",
    line_start: "11",
    line_end: "11",
    quote_text: "其鸣喈喈",
    category: "古典诗句",
    source_or_origin: "《诗经·周南·葛覃》句，原书引述",
    summary: "李敖引用《诗经》句说明早期诗歌绘声方式。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-201",
    book: "李敖语录",
    chapter: "论中国文学",
    source_file: "021.论中国文学.txt",
    line_start: "11",
    line_end: "11",
    quote_text: "灼灼其华",
    category: "古典诗句",
    source_or_origin: "《诗经·周南·桃夭》句，原书引述",
    summary: "李敖引用《诗经》句说明早期诗歌绘色方式。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-202",
    book: "李敖语录",
    chapter: "男女之间",
    source_file: "027.男女之间.txt",
    line_start: "87",
    line_end: "87",
    quote_text: "她若守节，上前相认；她若失节，将她杀死，去见我那代战公主。",
    category: "戏曲道白",
    source_or_origin: "平剧《武家坡》道白，原书明注",
    summary: "李敖引用《武家坡》道白批评片面的贞操观念。",
    notes: "校对轮补入；戏曲引用。",
  },
  {
    id: "LALAYL-203",
    book: "李敖语录",
    chapter: "灵肉问题",
    source_file: "028.灵肉问题.txt",
    line_start: "111",
    line_end: "111",
    quote_text: "有甚于画眉者",
    category: "古典成句",
    source_or_origin: "张敞画眉典故成句，原书引述",
    summary: "李敖引用画眉典故谈男女之事。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-204",
    book: "李敖语录",
    chapter: "论女性·论选美",
    source_file: "029.论女性·论选美.txt",
    line_start: "213",
    line_end: "213",
    quote_text: "有美玉如斯，……沽之哉！沽之哉！我待贾者也！",
    category: "古典文句",
    source_or_origin: "《论语·子罕》语，原书引述",
    summary: "李敖引用孔子“待贾”语比拟选美叫价心理。",
    notes: "校对轮补入。",
  },
  {
    id: "LALAYL-205",
    book: "李敖语录",
    chapter: "论女性·论选美",
    source_file: "029.论女性·论选美.txt",
    line_start: "239",
    line_end: "239",
    quote_text: "十目所视，十手所指",
    category: "古典文句",
    source_or_origin: "《大学》语，原书引述",
    summary: "李敖引用《大学》成句描写选美场合下的被观看。",
    notes: "校对轮补入。",
  },
];

const originalRows = parseCsv(fs.readFileSync(csvPath, "utf8"));
const additionIds = new Set(additions.map((row) => row.id));
const keptRows = originalRows.filter((row) => !removed.has(row.id) && !additionIds.has(row.id));
const rows = [...keptRows, ...additions].sort((left, right) => {
  const source = left.source_file.localeCompare(right.source_file, "zh-Hans-CN", {
    numeric: true,
  });
  if (source !== 0) return source;

  const line = Number(left.line_start) - Number(right.line_start);
  if (line !== 0) return line;

  const endLine = Number(left.line_end) - Number(right.line_end);
  if (endLine !== 0) return endLine;

  return left.id.localeCompare(right.id, "en", { numeric: true });
});

fs.writeFileSync(csvPath, stringifyCsv(rows), "utf8");

const baselineRows = keptRows.length + removed.size;

const reportLines = [
  "李敖语录 校对轮报告",
  "生成日期：2026-06-20",
  "",
  `原始条目：${baselineRows}`,
  `删除条目：${removed.size}`,
  `新增条目：${additions.length}`,
  `校对后条目：${rows.length}`,
  "",
  "删除项：",
  ...[...removed.entries()].map(([id, reason]) => `- ${id}：${reason}`),
  "",
  "新增项：",
  ...additions.map(
    (row) =>
      `- ${row.id}｜${row.source_file}:${row.line_start}-${row.line_end}｜${row.category}｜${row.quote_text}`,
  ),
  "",
  "校对说明：",
  "- 未补入丘吉尔、罗斯福、林肯等现代政治人物或政治章节中的政治性发言。",
  "- 未补入标题、自况、李敖本人情书/日记式语句，以及独立性不足的短碎片。",
  "- 新增项集中在古典诗文、宗教经典译句、戏曲道白、传统俗语与少量外国文学语。",
];

fs.writeFileSync(reportPath, reportLines.join("\n") + "\n", "utf8");

console.log(
  JSON.stringify(
    {
      originalRows: baselineRows,
      removedRows: removed.size,
      addedRows: additions.length,
      finalRows: rows.length,
      csvPath,
      reportPath,
    },
    null,
    2,
  ),
);

