const fs = require("fs");
const path = require("path");

const book = "论定蒋经国";
const idPrefix = "LALDJJG";
const generatedDate = "2026-06-28";
const sourceDir = path.join("《大李敖全集6.0》分章节", "012.人物研究类", "025.论定蒋经国");
const outCsv = path.join("exports", `${book}_诗文格言歌谣引用.csv`);
const outTxt = path.join("exports", `${book}_诗文格言歌谣引用.txt`);
const candidatesJson = path.join("analysis", "liao_lunding_chiang_ching_kuo_quote_candidates.json");
const reviewCandidatesTsv = path.join("analysis", "liao_lunding_chiang_ching_kuo_review_candidates.tsv");
const attributedTsv = path.join("analysis", "liao_lunding_chiang_ching_kuo_attributed_lines.tsv");
const selectedJson = path.join("analysis", "liao_lunding_chiang_ching_kuo_selected_rows.json");
const reviewTsv = path.join("analysis", "liao_lunding_chiang_ching_kuo_initial_review.tsv");
const auditTsv = path.join("analysis", "liao_lunding_chiang_ching_kuo_initial_audit.tsv");
const reportTxt = path.join("analysis", "liao_lunding_chiang_ching_kuo_initial_report.txt");
const proofreadReviewTsv = path.join("analysis", "liao_lunding_chiang_ching_kuo_proofread_review.tsv");
const proofreadAuditTsv = path.join("analysis", "liao_lunding_chiang_ching_kuo_proofread_audit.tsv");
const proofreadReportTxt = path.join("analysis", "liao_lunding_chiang_ching_kuo_proofread_report.txt");
const sourceDecoder = new TextDecoder("gb18030");

const files = fs
  .readdirSync(sourceDir)
  .filter((name) => name.endsWith(".txt") && !name.includes("目录"))
  .sort((a, b) => a.localeCompare(b, "zh-Hans-CN"));

const sourceCache = new Map();
for (const file of files) {
  const text = sourceDecoder.decode(fs.readFileSync(path.join(sourceDir, file)));
  sourceCache.set(file, { text, lines: text.split(/\r?\n/) });
}

function sourceFile(selector) {
  if (selector === "前言") return "《论定蒋经国》前言（李敖）.txt";
  const found = files.find((file) => file.startsWith(selector));
  if (!found) throw new Error(`Source file not found for selector: ${selector}`);
  return found;
}

function chapterName(file) {
  return file.replace(/^\d+\./, "").replace(/\.txt$/, "");
}

function normalizeText(text) {
  return String(text)
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n")
    .replace(/[“”‘’"'\u300c\u300d\u300e\u300f]/g, "")
    .replace(/\s+/g, "");
}

function q(selector, lineStart, quoteText, category, attributedTo, summary, lineEnd = lineStart, extraNotes = "") {
  const file = sourceFile(selector);
  return {
    id: "",
    book,
    chapter: chapterName(file),
    source_file: file,
    line_start: lineStart,
    line_end: lineEnd,
    quote_text: quoteText,
    category,
    source_or_origin: attributedTo,
    summary,
    notes: [
      "保守收入：《论定蒋经国》以蒋经国死后论定、蒋家父子、国民党党政军、青年军、赣南统治、金圆券、台湾政治和江南案为主体；现代党派、政权、领袖、总统、军政、战争、革命、国家民族、外交、统独、宪政、人权、意识形态、暗杀、接班与反蒋/拥蒋语录不收，只保留可脱离具体政治攻防独立检索的古典诗文、礼制文句、成语、俗语、题联、文学引文、家训和非政治格言。",
      extraNotes,
    ]
      .filter(Boolean)
      .join(" "),
  };
}

const rawRows = [
  q(
    "前言",
    7,
    "富贵不能淫、贫贱不能移、威武不能屈",
    "孟子名句",
    "《孟子·滕文公下》",
    "李敖引用孟子关于大丈夫不可被富贵、贫贱、威武动摇的名句。",
    7,
    "只收孟子名句本体；不收李敖鞭尸、国民党和民进党政治攻防语境。",
  ),
  q(
    "001.",
    15,
    "贫僧塔坏，陛下社稷随坏。",
    "佛教传说文句",
    "志公答梁武帝语",
    "李敖引志公回答梁武帝的预言式文句，说明塔坏与社稷相连。",
    15,
    "只收古代佛教传说文句；不收蒋氏父子亡国比附语境。",
  ),
  q(
    "001.",
    15,
    "六帝园林堕劫灰，独余静谷葬崔嵬，行人指点云间鹤，唤得齐梁一梦回。",
    "宋诗句",
    "宋人题灵谷寺诗",
    "李敖引用宋人题灵谷寺诗，写六朝兴亡与齐梁旧梦。",
    15,
    "只收题寺诗句本体；不收陈布雷、南京和蒋介石政治比附语境。",
  ),
  q(
    "001.",
    17,
    "一介有能，片言可用，朕亲加听览",
    "帝王诏令句",
    "陈后主诏令",
    "李敖引陈后主诏令，说明一人一言若可用也会亲自听览。",
    17,
    "只收古代诏令句本体；不收陈后主与蒋氏父子的现代政治比较。",
  ),
  q(
    "001.",
    19,
    "因失江山，无面目见祖宗于天上，不敢终于正寝",
    "史传文句",
    "崇祯遗言相关记载",
    "李敖引崇祯亡国时无面目见祖宗、不敢终于正寝的文句。",
    19,
    "只收古史文句；不收蒋介石亡国评价语境。",
  ),
  q(
    "001.",
    19,
    "自去冠冕，以发覆面",
    "史传文句",
    "崇祯殉国记载",
    "李敖引崇祯去冠覆面的殉国记载。",
    19,
    "只收古史文句；不收现代政治人物比附语境。",
  ),
  q(
    "001.",
    19,
    "国君死社稷，朕将安往？",
    "古代帝王语",
    "崇祯语",
    "李敖引崇祯拒绝南逃、称国君应死社稷的语句。",
    19,
    "只收古代帝王语本体；不收蒋氏父子亡国评议语境。",
  ),
  q(
    "001.",
    29,
    "乐不思蜀",
    "成语",
    "刘禅典故",
    "李敖用成语指刘禅不再思念蜀地。",
    29,
    "只收成语典故本体；不收蒋经国台湾人谈话和统独攻防语境。",
  ),
  q(
    "002.",
    17,
    "声妓晚景从良，一世之烟花无碍；贞妇白头失守，半生之清苦俱非。",
    "俗谚格言",
    "传统俗谚",
    "李敖引俗谚说明晚节从良与白头失守在评价上的反差。",
    17,
    "只收俗谚本体；不收蒋经国晚年开放党禁、报禁等政治论证。",
  ),
  q(
    "002.",
    17,
    "看人只看后半截。",
    "俗语",
    "中文俗语",
    "李敖引俗语说明评价人物只看后半段的说法。",
    17,
    "只收俗语本体；不收蒋经国政治评价语境。",
  ),
  q(
    "002.",
    19,
    "朕即位以来，所为狂悖，使天下愁苦，不可追悔，自今事有伤害百姓、靡费天下者，悉罢之！",
    "汉代诏书句",
    "汉武帝轮台罪己诏",
    "李敖引汉武帝罪己诏，写即位以来所为使天下愁苦并要求罢除伤民靡费之事。",
    19,
    "只收古代诏书句；不收蒋经国民主、人权和宪政现代政治评价语境。",
  ),
  q(
    "002.",
    23,
    "重为惠，若重为暴",
    "淮南子名句",
    "《淮南子》",
    "李敖引《淮南子》说明施惠也应像作恶一样不轻易。",
    23,
    "只收古典名句本体；不收亲民秀和现代政治治理批评语境。",
  ),
  q(
    "002.",
    23,
    "无智，故能使众智也；无能，故能使众能也；无为，故能使众为也。",
    "淮南子名句",
    "《淮南子》",
    "李敖引《淮南子》三无之说，说明不自炫聪明能力与作为，才能使众人发挥。",
    23,
    "只收古典名句本体；不收蒋经国下乡作秀和领袖政治语境。",
  ),
  q(
    "003.",
    17,
    "读书总以烂熟为度",
    "读书格言",
    "蒋介石家训文字",
    "作者引蒋介石训勉少年经国读书以烂熟为准的句子。",
    17,
    "只收读书格言本体；不收蒋家父子和政治人物身世语境。",
  ),
  q(
    "004.",
    9,
    "身体发肤，受之父母，不敢毁伤，孝之始也；立身行道，扬名于后世，以显父母，孝之终也！",
    "孝经名句",
    "《孝经》",
    "作者引《孝经》说明孝始于不毁伤身体发肤，终于立身扬名以显父母。",
    9,
    "只收孝经名句本体；不收蒋经国显父显母和国家元首语境。",
  ),
  q(
    "004.",
    21,
    "清明在躬，仪矩咸宜",
    "墓志文句",
    "吴稚晖《蒋经国母氏毛太君传》",
    "作者引吴稚晖文字说明毛从清之名取清明在躬、仪矩咸宜之意。",
    21,
    "只收墓志文句本体；不收蒋家亲属传记语境。",
  ),
  q(
    "004.",
    29,
    "昏定晨省",
    "孝道成语",
    "传统孝道成语",
    "作者引墓志文字中昏定晨省之语，写子妇侍奉长辈的礼节。",
    29,
    "只收成语本体；不收蒋家家族传记语境。",
  ),
  q(
    "004.",
    29,
    "有其父者，必有其子",
    "成句",
    "传统父子成句",
    "作者引吴稚晖墓志文字中有其父者必有其子的成句。",
    29,
    "只收成句本体；不收蒋氏父子政治身份语境。",
  ),
  q(
    "004.",
    35,
    "临难不苟免",
    "成语",
    "中文成语",
    "作者引吴稚晖文字称毛太君临难不苟免。",
    35,
    "只收成语本体；不收西安事变、日机轰炸和蒋家政治叙事语境。",
  ),
  q(
    "004.",
    89,
    "不但可以暖我身，而更可以温我心",
    "散文句",
    "蒋经国《东望章贡合流写给赣南的朋友们》",
    "作者引蒋经国写母亲棉背心不但暖身、更能温心的散文句。",
    89,
    "只收母子亲情散文句；不收蒋家政治身份语境。",
  ),
  q(
    "004.",
    91,
    "慈母手中线，游子身上衣",
    "唐诗名句",
    "孟郊《游子吟》",
    "作者化用孟郊诗句，说明慈母亲制衣物与游子情感。",
    91,
    "只收唐诗名句本体；不收蒋经国母子和政治人物传记语境。",
  ),
  q(
    "004.",
    105,
    "大丈夫三父八母",
    "民俗俗语",
    "中国民俗俗语",
    "作者引民俗俗语，说明大丈夫有三父八母之说。",
    105,
    "只收民俗俗语本体；不收蒋家母系身份论证语境。",
  ),
  q(
    "004.",
    105,
    "父母天地",
    "礼记成句",
    "《礼记》相关说法",
    "作者引《礼记》所说父母天地，说明本生母的根本地位。",
    105,
    "只收礼记成句本体；不收蒋经国母亲身份讨论语境。",
  ),
  q(
    "007.",
    21,
    "敬老尊贤",
    "成语",
    "中文成语",
    "作者用成语概括尊敬老人、尊重贤者的传统作风。",
    21,
    "只收成语本体；不收赣南统治、蒋青天和政治宣传语境。",
  ),
  q(
    "007.",
    21,
    "除暴安良",
    "成语",
    "中文成语",
    "作者用成语概括铲除强暴、安抚良善。",
    21,
    "只收成语本体；不收赣南地方治理和政治口号语境。",
  ),
  q(
    "009.",
    15,
    "谁能用人，谁就成功",
    "用人格言",
    "蒋经国言论",
    "作者引蒋经国关于会用人者才能成功的用人格言。",
    15,
    "只收用人格言本体；不收赣南干部培植和政治组织语境。",
  ),
  q(
    "009.",
    15,
    "要成就伟大事业，第一要有能干的人，第二要有能干的人，第三还是要有能干的人",
    "用人格言",
    "蒋经国言论",
    "作者引蒋经国反复强调能干人才对于成就事业的重要性。",
    15,
    "只收用人格言本体；不收干部训练、赣南统治和政治组织语境。",
  ),
  q(
    "011.",
    3,
    "暮宿石壕村，有吏夜捉人",
    "杜甫诗句",
    "杜甫《石壕吏》",
    "作者引杜甫《石壕吏》名句，写有吏夜间捉人的情景。",
    3,
    "只收杜甫诗句本体；不收赣南征兵与兵役行政语境。",
  ),
  q(
    "011.",
    3,
    "昔日石壕吏捉人，尚获老妇。今日之赣南，虽老妇亦戛戛乎其难矣！",
    "古诗化句",
    "化用杜甫《石壕吏》",
    "作者引诉状化用《石壕吏》之句，写昔日尚获老妇、今日连老妇也难得。",
    3,
    "只收古诗化句本体；不收赣南征兵和军政批评语境。",
  ),
  q(
    "011.",
    3,
    "当官不与民作主，不如回家卖红薯。",
    "民间谚语",
    "中文民间谚语",
    "作者引民谚说明做官若不替百姓作主，不如回家卖红薯。",
    3,
    "只收民谚本体；不收蒋经国改革兵役和地方治理语境。",
  ),
  q(
    "011.",
    5,
    "爱民如子",
    "成语",
    "中文成语",
    "作者引成语形容像爱护子女一样爱护百姓。",
    5,
    "只收成语本体；不收专员、法院和司法行政语境。",
  ),
  q(
    "011.",
    5,
    "秦镜高悬",
    "成语",
    "秦镜典故",
    "作者引成语形容明察是非、判案公正。",
    5,
    "只收成语本体；不收地方司法和政治人物吹捧语境。",
  ),
  q(
    "011.",
    5,
    "明察秋毫",
    "成语",
    "中文成语",
    "作者引成语形容观察细微、洞察清楚。",
    5,
    "只收成语本体；不收蒋经国地方司法判断语境。",
  ),
  q(
    "011.",
    5,
    "不在其位，不谋其政",
    "论语成句",
    "《论语》",
    "作者用《论语》成句说明不在其职位就不谋其政事。",
    5,
    "只收论语成句本体；不收军政和民刑案件语境。",
  ),
  q(
    "012.",
    5,
    "占山为王",
    "成语",
    "中文成语",
    "作者用成语形容据地自立、各自为势。",
    5,
    "只收成语本体；不收山东省政府、战区和特工活动语境。",
  ),
  q(
    "012.",
    5,
    "各霸一方",
    "成语",
    "中文成语",
    "作者用成语形容各自占据一方称霸。",
    5,
    "只收成语本体；不收地方武装和军政势力语境。",
  ),
  q(
    "012.",
    5,
    "尾大不掉",
    "成语",
    "中文成语",
    "作者用成语形容属下势力过大而难以指挥。",
    5,
    "只收成语本体；不收鲁苏战区和派系政治语境。",
  ),
  q(
    "012.",
    5,
    "朝不保夕",
    "成语",
    "中文成语",
    "作者用成语形容处境危险、早晨难保晚上。",
    5,
    "只收成语本体；不收战区困境和内调政治目的语境。",
  ),
  q(
    "015.",
    7,
    "投笔从戎",
    "成语",
    "班超投笔典故",
    "作者用成语说明弃文从军。",
    7,
    "只收成语典故本体；不收青年军征集和抗战宣传口号语境。",
  ),
  q(
    "016.",
    83,
    "人地不宜",
    "成语",
    "中文成语",
    "作者引用以人地不宜为由调派工作的说法。",
    83,
    "只收成语本体；不收青年军政工和派系处置语境。",
  ),
  q(
    "016.",
    85,
    "急流勇退",
    "成语",
    "中文成语",
    "作者用成语说明在险局中及时退身。",
    85,
    "只收成语本体；不收青年军腐化和复员复职语境。",
  ),
  q(
    "016.",
    85,
    "收回成命",
    "成语",
    "中文成语",
    "作者用成语说明请求撤回已经作出的命令。",
    85,
    "只收成语本体；不收青年军人事命令语境。",
  ),
  q(
    "016.",
    87,
    "安身立命",
    "成语",
    "中文成语",
    "作者用成语说明谋求立身处世的归宿。",
    87,
    "只收成语本体；不收战后去留和个人出路语境。",
  ),
  q(
    "019.",
    31,
    "失之东隅，收之桑榆",
    "古典成语",
    "《后汉书》成句",
    "作者用成语说明在一处失去而在另一处得到补偿。",
    31,
    "只收成语本体；不收太子系、政大和干部学校政治语境。",
  ),
  q(
    "023.",
    13,
    "五子登科",
    "俗语成语",
    "中文俗语",
    "作者用五子登科讽指抢金子、占房子、要车子、下馆子、住窑子等接收歪风。",
    13,
    "只收俗语本体；不收接收大员、贪污检举和军政人员语境。",
  ),
  q(
    "025.",
    5,
    "铁面无私",
    "成语",
    "中文成语",
    "作者用成语说明不讲情面、处事公正无私。",
    5,
    "只收成语本体；不收上海金圆券案和亲戚关系语境。",
  ),
  q(
    "026.",
    9,
    "驷不及舌",
    "古典成语",
    "《论语》相关成句",
    "作者用成语说明话已说出口，快马也追不上。",
    9,
    "只收成语本体；不收新币制、财政部和经济管制语境。",
  ),
  q(
    "026.",
    17,
    "晴天霹雳",
    "成语",
    "中文成语",
    "作者用成语形容突如其来的重大打击。",
    17,
    "只收成语本体；不收报纸攻击和金圆券案语境。",
  ),
  q(
    "026.",
    17,
    "丈二和尚摸不着头脑",
    "俗语",
    "中文俗语",
    "作者用俗语形容完全摸不清缘由。",
    17,
    "只收俗语本体；不收金融案和特务攻击语境。",
  ),
  q(
    "026.",
    19,
    "和盘托出",
    "成语",
    "中文成语",
    "作者用成语说明把情况全部说出。",
    19,
    "只收成语本体；不收银行外汇申报和经济管制语境。",
  ),
  q(
    "026.",
    27,
    "无稽之谈",
    "成语",
    "中文成语",
    "作者用成语称没有根据的说法。",
    27,
    "只收成语本体；不收《大众夜报》攻击和蒋经国讯问语境。",
  ),
  q(
    "026.",
    39,
    "为所欲为",
    "成语",
    "中文成语",
    "作者用成语形容想做什么就做什么。",
    39,
    "只收成语本体；不收蒋经国、银行查账和特务横行语境。",
  ),
  q(
    "028.",
    21,
    "用高射炮打蚊子",
    "俗语",
    "中文俗语",
    "作者引用俗语，形容用过大的力量对付很小的对象。",
    21,
    "只收俗语本体；不收新生报、吴惊鸿和权贵关系语境。",
  ),
  q(
    "028.",
    29,
    "但愿生女不生男",
    "古诗化句",
    "白居易《长恨歌》化用",
    "作者化用但愿生女不生男之句，形容旁人羡慕女演员得势。",
    29,
    "只收诗句化用本体；不收吴惊鸿、政治花柳科和权贵电影语境。",
  ),
  q(
    "029.",
    27,
    "功高震主",
    "成语",
    "中文成语",
    "作者用成语形容功劳过高而使主上猜忌。",
    27,
    "只收成语本体；不收蒋经国用人哲学和政坛人事语境。",
  ),
  q(
    "029.",
    33,
    "乔太守乱点鸳鸯谱",
    "戏曲典故",
    "传统戏曲《乔太守乱点鸳鸯谱》",
    "作者借戏曲典故说明胡乱安排、乱点鸳鸯的情形。",
    33,
    "只收戏曲典故本体；不收人事安排和政坛派系语境。",
  ),
  q(
    "029.",
    37,
    "朝秦暮楚",
    "成语",
    "战国典故",
    "作者用成语形容立场或安排反复变动。",
    37,
    "只收成语本体；不收蒋经国组阁和人事安排语境。",
  ),
  q(
    "029.",
    43,
    "一而再，再而三",
    "成语",
    "中文成语",
    "作者用成语形容反复多次遭遇挫折。",
    43,
    "只收成语本体；不收仕途等待和政坛人事语境。",
  ),
  q(
    "029.",
    45,
    "赵孟能贵之，亦能贱之",
    "古典成句",
    "《孟子》相关典故",
    "作者引用赵孟能使人贵也能使人贱的古典成句。",
    45,
    "只收古典成句本体；不收蒋经国权力分配和用人政策语境。",
  ),
  q(
    "029.",
    45,
    "人在江湖，身不由己",
    "俗语",
    "中文俗语",
    "作者用俗语说明人在环境中常不能自主。",
    45,
    "只收俗语本体；不收官场和权力核心语境。",
  ),
  q(
    "029.",
    45,
    "六宫粉黛无颜色",
    "唐诗名句",
    "白居易《长恨歌》",
    "作者化用白居易诗句形容得宠时光彩压过众人。",
    45,
    "只收唐诗名句本体；不收官场得失和政坛人事语境。",
  ),
  q(
    "029.",
    45,
    "明日巴陵道，秋山又几重",
    "唐诗句",
    "李益《喜见外弟又言别》",
    "作者引用唐诗句，写失意离别、前路山重的感慨。",
    45,
    "只收唐诗句本体；不收官场失意和人事安排语境。",
  ),
  q(
    "029.",
    47,
    "赏赐的是耶和华，收回的也是祂，耶和华的名是值得称颂的",
    "圣经句",
    "《约伯记》",
    "作者引用《约伯记》关于赐予与收回皆出于耶和华的句子。",
    47,
    "只收圣经句本体；不收权力得失和高官起落语境。",
  ),
  q(
    "029.",
    53,
    "不求有功，但求无过",
    "俗语成句",
    "中文俗语",
    "作者用俗语形容只求不出错而不求建功。",
    53,
    "只收俗语本体；不收权力变幻和官场心态语境。",
  ),
  q(
    "032.",
    9,
    "孤掌难鸣",
    "成语",
    "中文成语",
    "作者用成语说明单靠一只手掌难以拍响，单人难成事。",
    9,
    "只收成语本体；不收台湾经济成就和政治人物功劳归属语境。",
  ),
  q(
    "032.",
    9,
    "众擎易举",
    "成语",
    "中文成语",
    "作者用成语说明众人合力就容易举起重物。",
    9,
    "只收成语本体；不收经济成就与政治归功语境。",
  ),
  q(
    "032.",
    11,
    "醉翁之意不在酒",
    "成语",
    "欧阳修《醉翁亭记》成句",
    "作者用成语说明表面行为之外另有目的。",
    11,
    "只收成语本体；不收蒋经国下乡和政治作秀语境。",
  ),
  q(
    "032.",
    11,
    "黄老之术",
    "古典思想成语",
    "黄老思想",
    "作者用黄老之术指称黄老无为的治术。",
    11,
    "只收古典思想成语；不收勤政作秀和现代治理语境。",
  ),
  q(
    "032.",
    11,
    "无为而治",
    "道家成语",
    "道家政治哲学成句",
    "作者用成语说明顺应自然、不多干预而达到治理。",
    11,
    "只收古典成语本体；不收现代政治治理争论语境。",
  ),
  q(
    "032.",
    21,
    "百足之虫，死而不僵",
    "成语",
    "中文成语",
    "作者用成语形容势力虽衰亡仍未完全消失。",
    21,
    "只收成语本体；不收蒋氏父子权势和政治哀悼语境。",
  ),
  q(
    "033.",
    5,
    "人死了，只能讲他的好话",
    "丧葬俗见",
    "中文丧葬俗见",
    "李敖概括人死后只能讲好话的俗见。",
    5,
    "只收俗见本体；不收蒋经国死后褒贬和政治评价语境。",
  ),
  q(
    "033.",
    5,
    "人死了，一切就都算了、被饶恕了",
    "丧葬俗见",
    "中文丧葬俗见",
    "李敖概括人死后一切都算了、应被饶恕的俗见。",
    5,
    "只收俗见本体；不收蒋经国死后政治评价语境。",
  ),
  q(
    "033.",
    5,
    "人死了，你可以不讲话，但不可以讲他坏话",
    "丧葬俗见",
    "中文丧葬俗见",
    "李敖概括人死后可以沉默但不可讲坏话的俗见。",
    5,
    "只收俗见本体；不收政治人物死后评价语境。",
  ),
  q(
    "033.",
    5,
    "代死者祷告",
    "宗教用语",
    "基督教传统 Prayer for the Departed",
    "李敖引基督教传统中代死者祷告的说法。",
    5,
    "只收宗教用语本体；不收蒋经国死后评价和政治褒贬语境。",
  ),
  q(
    "033.",
    5,
    "万世流芳",
    "成语",
    "中文成语",
    "李敖列举死者颂词中万世流芳的套语。",
    5,
    "只收成语本体；不收追悼颂词和现代政治人物语境。",
  ),
  q(
    "033.",
    5,
    "蒙主宠召",
    "宗教套语",
    "基督教丧葬用语",
    "李敖列举基督教丧葬语境中的蒙主宠召套语。",
    5,
    "只收宗教套语本体；不收政治人物死后颂扬语境。",
  ),
  q(
    "035.",
    9,
    "危国之祸，不及其家。",
    "古典道德成句",
    "王充《论衡·定贤篇》相关成句",
    "作者引中国固有道德中危国之祸不及其家的成句。",
    9,
    "只收古典成句本体；不收蒋经国遗族、政治冤狱和祈祷语境。",
  ),
  q(
    "035.",
    9,
    "大贤涉世也，翔而有集，色斯而举。乱君之患，不累其身，危国之祸，不及其家，安得逢其祸而死其患乎？",
    "论衡文句",
    "王充《论衡·定贤篇》",
    "作者引用王充《论衡》论大贤涉世、乱君之患与危国之祸的文句。",
    9,
    "只收古典文句本体；不收蒋家遗族和现代政治冤狱语境。",
  ),
  q(
    "035.",
    9,
    "宗庙有灵存社稷，英宗无意杀先生。",
    "清诗句",
    "秦松龄《于忠肃公墓》",
    "作者引秦松龄诗句，写宗庙社稷与英宗杀于谦之事。",
    9,
    "只收清诗句本体；不收现代政治人物和冤狱语境。",
  ),
  q(
    "035.",
    9,
    "里有殡，不巷歌！",
    "礼记名句",
    "《礼记》",
    "作者引《礼记》里有丧殡时巷中不歌的礼制名句。",
    9,
    "只收礼记名句本体；不收蒋经国死后祈祷和政治评价语境。",
  ),
  q(
    "035.",
    13,
    "廿年三字冤沉海，一别千秋恨怎平！",
    "挽诗句",
    "现代挽诗句",
    "作者引诗句写多年冤屈沉海、一别千秋的悲恨。",
    13,
    "只收挽诗句本体；不收政治冤狱和国民党忠贞同志语境。",
  ),
  q(
    "036.",
    15,
    "三年无改于父之道，可谓孝矣！",
    "论语名句",
    "《论语·学而》",
    "作者引孔子语，说明三年不改父道可称为孝。",
    15,
    "只收论语名句本体；不收蒋家宗教信仰和政治人物丧后语境。",
  ),
  q(
    "036.",
    15,
    "风调雨顺",
    "成语",
    "中文成语",
    "作者引匾额中的风调雨顺成语。",
    15,
    "只收成语本体；不收妈祖庙、行政院长和政治人物信仰语境。",
  ),
  q(
    "037.",
    15,
    "瞒官骗鬼",
    "闽南谚语",
    "闽南谚语",
    "作者引闽南谚语，骂人爱说谎到连官和鬼都要瞒骗。",
    15,
    "只收谚语本体；不收新闻局、病情公告和政治隐瞒语境。",
  ),
  q(
    "037.",
    25,
    "尸居余气",
    "成语",
    "中文成语",
    "作者用成语形容只剩微弱气息的状态。",
    25,
    "只收成语本体；不收蒋经国健康状况和官方声明语境。",
  ),
  q(
    "037.",
    31,
    "撒谎的人，要有好的记忆力。",
    "格言",
    "李敖语",
    "作者引用李敖关于撒谎者需要好记忆力的格言。",
    31,
    "只收格言本体；不收新闻局长、总统病情和政治发言语境。",
  ),
  q(
    "039.",
    13,
    "苟存性命于乱世",
    "出师表名句",
    "诸葛亮《出师表》",
    "李敖化用《出师表》苟全性命于乱世的名句。",
    13,
    "只收古典名句片段；不收江南案、暗杀和现代政治安全语境。",
  ),
  q(
    "039.",
    13,
    "闻达于诸侯",
    "出师表名句",
    "诸葛亮《出师表》",
    "李敖化用《出师表》不求闻达于诸侯的名句片段。",
    13,
    "只收古典名句片段；不收李敖知名度和政治安全语境。",
  ),
  q(
    "039.",
    13,
    "此度见花枝，白头誓不归",
    "古诗句",
    "古人发愿诗句",
    "李敖引用古人发愿诗句，写此番见花枝后白头也不归。",
    13,
    "只收古诗句本体；不收江南离台、国民党和暗杀语境。",
  ),
  q(
    "039.",
    13,
    "魂兮魂兮，不必归来",
    "楚辞化句",
    "《楚辞·招魂》化用",
    "李敖化用招魂句式，写魂兮魂兮、不必归来。",
    13,
    "只收楚辞化句本体；不收江南身死异域和政治暗杀语境。",
  ),
  q(
    "039.",
    39,
    "一手遮天",
    "成语",
    "中文成语",
    "李敖用成语形容企图遮蔽真相。",
    39,
    "只收成语本体；不收江南案真凶层次和审判政治语境。",
  ),
  q(
    "039.",
    39,
    "欲盖弥彰",
    "成语",
    "中文成语",
    "李敖用成语说明越想掩盖反而越显露。",
    39,
    "只收成语本体；不收国民党情报员说法和江南案政治语境。",
  ),
  q(
    "039.",
    59,
    "人生如春蚕，作茧自缠裹。一朝眉羽成，钻破亦在我。",
    "宋诗句",
    "陆游诗句",
    "李敖引用陆游诗句，写人生如春蚕作茧，羽成后钻破亦在自身。",
    59,
    "只收陆游诗句本体；不收江南成长、干校和海外流亡语境。",
  ),
  q(
    "039.",
    67,
    "字字看来皆是血",
    "红楼梦名句",
    "曹雪芹《红楼梦》自题诗化用",
    "李敖化用字字看来皆是血，称江南以血的代价成全其书。",
    67,
    "只收文学名句本体；不收江南遇害和政治暗杀语境。",
  ),
];

const proofreadRemovedQuoteTexts = new Set(
  [
    "谁能用人，谁就成功",
    "要成就伟大事业，第一要有能干的人，第二要有能干的人，第三还是要有能干的人",
  ].map(normalizeText),
);

const proofreadRemovedRows = rawRows
  .filter((row) => proofreadRemovedQuoteTexts.has(normalizeText(row.quote_text)))
  .map((row) => ({
    ...row,
    proofread_action: "remove",
    proofread_reason: "校对轮移除：原文明确归为蒋经国多次演讲和言论中的干部/用人格言，按现代政治人物语录从严不收。",
  }));

const proofreadAdditions = [
  q(
    "001.",
    19,
    "好似门神",
    "典故成语",
    "崇祯私语典故",
    "李敖引崇祯称王洽好似门神，取一年一换、任用不久之意。",
    19,
    "校对轮增补：只收典故短语本体；不收明亡与蒋氏父子政治比附语境。",
  ),
  q(
    "001.",
    25,
    "扶不起的阿斗",
    "俗语典故",
    "刘禅典故",
    "李敖用扶不起的阿斗形容后主刘禅难以成器的俗语典故。",
    25,
    "校对轮增补：只收三国俗语典故本体；不收蒋经国、邓小平和国共派系比较语境。",
  ),
  q(
    "002.",
    5,
    "炳耀千秋",
    "成语",
    "中文成语",
    "李敖摘出炳耀千秋一语，指称历史上长久显耀的评价套语。",
    5,
    "校对轮增补：只收评价成语本体；不收对现代政治人物的歌功颂德语境。",
  ),
  q(
    "002.",
    5,
    "有过之而无不及",
    "成语",
    "中文成语",
    "李敖用有过之而无不及表示程度超过而不是不如。",
    5,
    "校对轮增补：只收通用成语本体；不收石敬瑭、蒋氏父子卖国比较语境。",
  ),
  q(
    "002.",
    5,
    "高朗令终",
    "史传评语",
    "《旧五代史》评石敬瑭语",
    "李敖引《旧五代史》高朗令终一语，作为古史人物结局评价。",
    5,
    "校对轮增补：只收古史评语本体；不收现代政治评价语境。",
  ),
  q(
    "002.",
    17,
    "与人为善",
    "成语",
    "中文成语",
    "李敖用与人为善表示以善意看待他人的说法。",
    17,
    "校对轮增补：只收通用成语本体；不收开放党禁报禁的政治评价语境。",
  ),
  q(
    "002.",
    17,
    "辣手摧花",
    "成语",
    "中文成语",
    "李敖用辣手摧花比喻长期残害美好事物。",
    17,
    "校对轮增补：只收成语本体；不收台湾政治攻防语境。",
  ),
  q(
    "002.",
    17,
    "怜香惜玉",
    "成语",
    "中文成语",
    "李敖用怜香惜玉比喻临末才表现出来的柔和姿态。",
    17,
    "校对轮增补：只收成语本体；不收台湾政治攻防语境。",
  ),
  q(
    "004.",
    29,
    "纤屑曲尽",
    "墓志文句",
    "吴稚晖《蒋经国母毛太君传》",
    "李敖引吴稚晖墓志文字，写毛太君侍奉长辈时细微处都周到。",
    29,
    "校对轮增补：只收墓志文句本体；不收蒋家家族身世语境。",
  ),
  q(
    "004.",
    41,
    "方正贤良",
    "题名成句",
    "蒋方良赐名取义",
    "李敖引蒋方良名字取方正贤良之意的成句。",
    41,
    "校对轮增补：只收命名取义短语；不收蒋家身份和政治年表语境。",
  ),
  q(
    "004.",
    41,
    "贤良慈孝",
    "题词成句",
    "蒋介石生日题词",
    "李敖引贤良慈孝题词，作为传统德目式祝词。",
    41,
    "校对轮增补：只收德目题词本体；不收题词者和政治身份语境。",
  ),
  q(
    "004.",
    79,
    "深夜自省，饮泪自痛",
    "日记文句",
    "蒋经国日记",
    "李敖引日记中深夜自省、饮泪自痛的哀思文句。",
    79,
    "校对轮增补：只收亲情哀思文句；不收外交特派员和政治身份语境。",
  ),
  q(
    "011.",
    5,
    "急如星火",
    "成语",
    "中文成语",
    "方暾用急如星火形容督征催迫的急切。",
    5,
    "校对轮增补：只收通用成语本体；不收征兵军政语境。",
  ),
  q(
    "011.",
    5,
    "作壁上观",
    "成语",
    "中文成语",
    "方暾用作壁上观形容旁观他人议案。",
    5,
    "校对轮增补：只收通用成语本体；不收赣南司法和军政语境。",
  ),
  q(
    "011.",
    5,
    "九霄云外",
    "成语",
    "中文成语",
    "方暾用九霄云外形容法律原则被抛到极远处。",
    5,
    "校对轮增补：只收通用成语本体；不收赣南司法和军政语境。",
  ),
  q(
    "011.",
    7,
    "走马上任",
    "成语",
    "中文成语",
    "方暾用走马上任形容刚到新职。",
    7,
    "校对轮增补：只收通用成语本体；不收上海经济管制政治语境。",
  ),
  q(
    "011.",
    7,
    "忠孝两全",
    "成语",
    "中文成语",
    "方暾引不能忠孝两全，表示忠与孝难以同时兼顾。",
    7,
    "校对轮增补：只收传统伦理成语本体；不收金圆券和家族权力语境。",
  ),
  q(
    "018.",
    57,
    "穆桂英挂帅",
    "戏曲典故",
    "京剧传统剧目",
    "夏明曦回忆晚会演出京剧《穆桂英挂帅》，形成可检索的戏曲典故。",
    57,
    "校对轮增补：只收戏曲剧目典故；不收重庆谈判和军政招待语境。",
  ),
  q(
    "026.",
    21,
    "虚与委蛇",
    "成语",
    "中文成语",
    "戴立庵引原文中的虚与委蛇，表示敷衍应付、拖延观望。",
    21,
    "校对轮增补：只收成语本体；不收金圆券和政府训话语境。",
  ),
  q(
    "026.",
    25,
    "霸王请客",
    "俗语",
    "中文俗语",
    "戴立庵用霸王请客形容强迫性质的约见。",
    25,
    "校对轮增补：只收俗语本体；不收上海金圆券约谈语境。",
  ),
  q(
    "026.",
    25,
    "吉少凶多",
    "成语",
    "中文成语",
    "戴立庵用吉少凶多形容前途凶险多于吉利。",
    25,
    "校对轮增补：只收通用成语本体；不收上海金圆券约谈语境。",
  ),
  q(
    "026.",
    31,
    "有恃无恐",
    "成语",
    "中文成语",
    "戴立庵引小报以有恃无恐形容受攻击者仍不害怕。",
    31,
    "校对轮增补：只收成语本体；不收金圆券舆论攻击语境。",
  ),
  q(
    "026.",
    35,
    "咎由自取",
    "成语",
    "中文成语",
    "戴立庵用咎由自取表示祸患由自身行为招致。",
    35,
    "校对轮增补：只收成语本体；不收蒋氏父子和金融资本语境。",
  ),
  q(
    "028.",
    23,
    "呼风唤雨",
    "成语",
    "中文成语",
    "郑经用呼风唤雨形容人物法力或影响力极大。",
    23,
    "校对轮增补：只收成语本体；不收影剧圈和政治花柳科语境。",
  ),
  q(
    "029.",
    37,
    "见光死",
    "俗语",
    "中文俗语",
    "赵达中用见光死形容人选曝光后反而落空。",
    37,
    "校对轮增补：只收俗语本体；不收权力安排和政坛人事语境。",
  ),
  q(
    "029.",
    43,
    "多如过江之鲫",
    "成语",
    "中文成语",
    "赵达中用多如过江之鲫形容数量很多。",
    43,
    "校对轮增补：只收成语本体；不收台湾政坛仕途语境。",
  ),
  q(
    "029.",
    45,
    "学富五车",
    "成语",
    "中文成语",
    "赵达中用学富五车形容学问丰富。",
    45,
    "校对轮增补：只收通用成语本体；不收高层权力核心语境。",
  ),
  q(
    "029.",
    49,
    "做官看运气，下台要有勇气。",
    "官场俗语",
    "中文官场俗语",
    "赵达中引仕途冷暖后的感慨，称做官看运气、下台要有勇气。",
    49,
    "校对轮增补：只收官场俗语本体；不收蒋经国用人和权力分配语境。",
  ),
  q(
    "029.",
    49,
    "迁客骚人",
    "文学成语",
    "范仲淹《岳阳楼记》语",
    "赵达中用迁客骚人形容宦途失意后有所感怀的人。",
    49,
    "校对轮增补：只收文学成语本体；不收仕途政治语境。",
  ),
  q(
    "029.",
    53,
    "五日京兆",
    "成语典故",
    "汉代京兆尹典故",
    "赵达中用五日京兆形容任职短暂、不能长久的心态。",
    53,
    "校对轮增补：只收成语典故本体；不收施政和权力流动语境。",
  ),
  q(
    "032.",
    11,
    "上下五千年、纵横八万里",
    "夸饰成句",
    "中文成句",
    "陈左弧用上下五千年、纵横八万里形容历史悠久、空间广阔。",
    11,
    "校对轮增补：只收夸饰成句本体；不收国家元首和政治作秀语境。",
  ),
  q(
    "032.",
    11,
    "鸣琴垂拱",
    "古典成语",
    "传统治世典故",
    "陈左弧用鸣琴垂拱指古代无为而治式的清静治世想象。",
    11,
    "校对轮增补：只收古典典故本体；不收现代政治制度争论语境。",
  ),
  q(
    "032.",
    11,
    "微服私访、勤求民隐",
    "古典政事成语",
    "传统帝王巡访套语",
    "陈左弧用微服私访、勤求民隐概括古代寻访民情的招式。",
    11,
    "校对轮增补：只收传统套语本体；不收现代政治作秀批评语境。",
  ),
  q(
    "032.",
    13,
    "剑及履及",
    "成语",
    "中文成语",
    "陈左弧用剑及履及形容事情必须立刻实际处理。",
    13,
    "校对轮增补：只收通用成语本体；不收陈情求助和行政语境。",
  ),
  q(
    "032.",
    19,
    "日食三餐，夜眠八尺",
    "俗语",
    "中文俗语",
    "陈左弧用日食三餐、夜眠八尺说明人生所需有限。",
    19,
    "校对轮增补：只收人生俗语本体；不收总统墓地和财产批评语境。",
  ),
  q(
    "032.",
    19,
    "立锥无地",
    "成语",
    "中文成语",
    "陈左弧用立锥无地形容连极小立足之地也没有。",
    19,
    "校对轮增补：只收成语本体；不收墓地土地政治批评语境。",
  ),
  q(
    "032.",
    21,
    "如丧考妣",
    "成语",
    "中文成语",
    "陈左弧用如丧考妣形容哀伤如同父母去世。",
    21,
    "校对轮增补：只收成语本体；不收蒋经国死后哀悼和政治评价语境。",
  ),
  q(
    "033.",
    5,
    "一代完人",
    "成语",
    "中文成语",
    "李敖用一代完人概括谀词造成的完美死者印象。",
    5,
    "校对轮增补：只收丧葬谀词成语本体；不收蒋经国死后评价语境。",
  ),
  q(
    "037.",
    25,
    "为天年所限",
    "文言成句",
    "传统文言成句",
    "李世杰用为天年所限表示寿命已到自然限度。",
    25,
    "校对轮增补：只收文言成句本体；不收总统健康声明语境。",
  ),
  q(
    "037.",
    25,
    "众目睽睽",
    "成语",
    "中文成语",
    "李世杰用众目睽睽表示在很多人注视之下。",
    25,
    "校对轮增补：只收成语本体；不收健康公告和官方文书语境。",
  ),
  q(
    "039.",
    13,
    "投鼠忌器",
    "成语",
    "中文成语",
    "李敖用投鼠忌器表示有所顾忌而不敢贸然下手。",
    13,
    "校对轮增补：只收成语本体；不收国民党暗杀和江南案语境。",
  ),
  q(
    "039.",
    13,
    "一语成谶",
    "成语",
    "中文成语",
    "李敖用一语成谶表示一句话后来不幸应验。",
    13,
    "校对轮增补：只收成语本体；不收江南遇害和政治暗杀语境。",
  ),
  q(
    "039.",
    21,
    "重如泰山",
    "成语",
    "司马迁《报任安书》相关成句",
    "李敖用重如泰山形容死亡或牺牲意义重大。",
    21,
    "校对轮增补：只收成语本体；不收江南之死和政治影响语境。",
  ),
  q(
    "039.",
    45,
    "似是而非",
    "成语",
    "中文成语",
    "李敖用似是而非形容看似有理实则不对的议论。",
    45,
    "校对轮增补：只收成语本体；不收竹联帮审判和政治抹黑语境。",
  ),
  q(
    "039.",
    45,
    "忘恩负义",
    "成语",
    "中文成语",
    "李敖引忘恩负义一语，指出被抹黑者遭到的道德指控。",
    45,
    "校对轮增补：只收成语本体；不收国民党和竹联帮相关政治语境。",
  ),
  q(
    "039.",
    45,
    "不知感恩图报",
    "俗语成句",
    "中文俗语",
    "李敖引不知感恩图报，作为道德指控式俗语。",
    45,
    "校对轮增补：只收俗语成句本体；不收国民党和竹联帮相关政治语境。",
  ),
  q(
    "039.",
    47,
    "天不怕地不怕",
    "俗语",
    "中文俗语",
    "李敖引天不怕地不怕，形容人无所畏惧的个性。",
    47,
    "校对轮增补：只收俗语本体；不收江南个人政治经历语境。",
  ),
  q(
    "039.",
    47,
    "疾恶如仇",
    "成语",
    "中文成语",
    "李敖引疾恶如仇，形容憎恶坏事如同仇敌。",
    47,
    "校对轮增补：只收成语本体；不收江南个人政治经历语境。",
  ),
];

if (proofreadRemovedRows.length !== proofreadRemovedQuoteTexts.size) {
  throw new Error(
    `Proofread removal target not found: expected ${proofreadRemovedQuoteTexts.size}, got ${proofreadRemovedRows.length}`,
  );
}

const modernPoliticalTerms = [
  "共产党",
  "共党",
  "中共",
  "共匪",
  "国民党",
  "民进党",
  "台独",
  "中华民国",
  "党国",
  "政府",
  "政权",
  "总统",
  "总裁",
  "领袖",
  "国父",
  "主席",
  "委员长",
  "行政院",
  "立法院",
  "国防部",
  "外交部",
  "军法",
  "军队",
  "特务",
  "反共",
  "革命",
  "三民主义",
  "主义",
  "战争",
  "抗战",
  "北伐",
  "内战",
  "反攻",
  "台湾",
  "大陆",
  "西藏",
  "外蒙",
  "美国",
  "日本",
  "苏联",
  "俄国",
  "暗杀",
  "战犯",
  "言论自由",
  "人权",
  "民主政治",
  "青年军",
  "金圆券",
  "接班",
];

function csvEscape(value) {
  const text = String(value ?? "");
  return /[",\r\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
}

function rowToCsv(row) {
  return [
    row.id,
    row.book,
    row.chapter,
    row.source_file,
    row.line_start,
    row.line_end,
    row.quote_text,
    row.category,
    row.source_or_origin,
    row.summary,
    row.notes,
  ]
    .map(csvEscape)
    .join(",");
}

function quotePresent(row) {
  const source = sourceCache.get(row.source_file);
  const slice = source.lines.slice(row.line_start - 1, row.line_end).join("\n");
  return normalizeText(slice).includes(normalizeText(row.quote_text));
}

function hasPoliticalHit(row) {
  return modernPoliticalTerms.filter((term) => row.quote_text.includes(term));
}

const fileIndex = new Map(files.map((file, index) => [file, index]));
const selectedRows = rawRows
  .filter((row) => !proofreadRemovedQuoteTexts.has(normalizeText(row.quote_text)))
  .concat(proofreadAdditions)
  .sort((a, b) => {
    const fileDiff = fileIndex.get(a.source_file) - fileIndex.get(b.source_file);
    if (fileDiff) return fileDiff;
    if (a.line_start !== b.line_start) return a.line_start - b.line_start;
    return a.quote_text.localeCompare(b.quote_text, "zh-Hans-CN");
  })
  .map((row, index) => ({
    ...row,
    id: `${idPrefix}-${String(index + 1).padStart(3, "0")}`,
  }));

const auditRows = selectedRows.map((row) => {
  const present = quotePresent(row);
  const politicalHits = hasPoliticalHit(row);
  return { row, present, politicalHits };
});

const missing = auditRows.filter((item) => !item.present);
const politicalHits = auditRows.filter((item) => item.politicalHits.length > 0);
const duplicateTexts = new Map();
for (const row of selectedRows) {
  const key = normalizeText(row.quote_text);
  duplicateTexts.set(key, (duplicateTexts.get(key) || 0) + 1);
}
const duplicates = selectedRows.filter((row) => duplicateTexts.get(normalizeText(row.quote_text)) > 1);
const proofreadAdditionKeys = new Set(proofreadAdditions.map((row) => normalizeText(row.quote_text)));
const proofreadAuditRows = [
  ...auditRows.map((item) => ({
    ...item,
    action: proofreadAdditionKeys.has(normalizeText(item.row.quote_text)) ? "add" : "keep",
    reason: proofreadAdditionKeys.has(normalizeText(item.row.quote_text))
      ? "校对轮增补：原文逐字命中，且可脱离具体现代政治语境独立检索。"
      : "校对轮保留：首轮条目复核后未发现需剔除的现代政治语录问题。",
  })),
  ...proofreadRemovedRows.map((row) => ({
    row,
    present: quotePresent(row),
    politicalHits: hasPoliticalHit(row),
    action: row.proofread_action,
    reason: row.proofread_reason,
  })),
].sort((a, b) => {
  const fileDiff = fileIndex.get(a.row.source_file) - fileIndex.get(b.row.source_file);
  if (fileDiff) return fileDiff;
  if (a.row.line_start !== b.row.line_start) return a.row.line_start - b.row.line_start;
  return a.row.quote_text.localeCompare(b.row.quote_text, "zh-Hans-CN");
});

if (missing.length) {
  throw new Error(`Missing quote text in source: ${missing.map((item) => item.row.id).join(", ")}`);
}
if (duplicates.length) {
  throw new Error(`Duplicate quote text in ${book}: ${duplicates.map((row) => row.id).join(", ")}`);
}
if (politicalHits.length) {
  throw new Error(
    `Political terms in selected quote text: ${politicalHits
      .map((item) => `${item.row.id}(${item.politicalHits.join("|")})`)
      .join(", ")}`,
  );
}

fs.mkdirSync(path.dirname(outCsv), { recursive: true });
fs.mkdirSync(path.dirname(selectedJson), { recursive: true });

const header = [
  "id",
  "book",
  "chapter",
  "source_file",
  "line_start",
  "line_end",
  "quote_text",
  "category",
  "source_or_origin",
  "summary",
  "notes",
].join(",");

fs.writeFileSync(outCsv, `${header}\n${selectedRows.map(rowToCsv).join("\n")}\n`, "utf8");

const txt = selectedRows
  .map((row) =>
    [
      `${row.id}｜${row.category}｜${row.source_file}:${row.line_start}-${row.line_end}`,
      `引用：${row.quote_text}`,
      `出处线索：${row.source_or_origin}`,
      `说明：${row.summary}`,
      row.notes ? `备注：${row.notes}` : "",
    ]
      .filter(Boolean)
      .join("\n"),
  )
  .join("\n\n");

fs.writeFileSync(outTxt, `${book} 诗文格言歌谣引用\n生成日期：${generatedDate}\n条目数：${selectedRows.length}\n\n${txt}\n`, "utf8");
fs.writeFileSync(selectedJson, `${JSON.stringify(selectedRows, null, 2)}\n`, "utf8");

fs.writeFileSync(
  proofreadReviewTsv,
  [
    "id\tsource_file\tline_start\tline_end\tcategory\tquote_text\tsource_or_origin\tsummary\tnotes",
    ...selectedRows.map((row) =>
      [
        row.id,
        row.source_file,
        row.line_start,
        row.line_end,
        row.category,
        row.quote_text,
        row.source_or_origin,
        row.summary,
        row.notes,
      ].join("\t"),
    ),
  ].join("\n") + "\n",
  "utf8",
);

fs.writeFileSync(
  proofreadAuditTsv,
  [
    "action\treason\tid\tsource_file\tline_start\tline_end\tpresent\tpolitical_hits\tquote_text",
    ...proofreadAuditRows.map((item) =>
      [
        item.action,
        item.reason,
        item.row.id,
        item.row.source_file,
        item.row.line_start,
        item.row.line_end,
        item.present ? "yes" : "no",
        item.politicalHits.join("|"),
        item.row.quote_text,
      ].join("\t"),
    ),
  ].join("\n") + "\n",
  "utf8",
);

const candidatesData = fs.existsSync(candidatesJson) ? JSON.parse(fs.readFileSync(candidatesJson, "utf8")) : null;
const quoteCandidates = Array.isArray(candidatesData)
  ? candidatesData.filter((row) => row.kind === "quote").length
  : candidatesData?.quoteCandidates?.length ?? "missing";
const keywordLines = Array.isArray(candidatesData)
  ? candidatesData.filter((row) => row.kind === "keyword_line").length
  : candidatesData?.keywordLines ?? "missing";
const uniqueQuoteTexts = Array.isArray(candidatesData)
  ? new Set(candidatesData.filter((row) => row.kind === "quote").map((row) => normalizeText(row.text ?? row.quote_text))).size
  : candidatesData?.uniqueQuoteTexts ?? "missing";
const reviewCandidateLines = fs.existsSync(reviewCandidatesTsv)
  ? fs.readFileSync(reviewCandidatesTsv, "utf8").trim().split(/\r?\n/).length - 1
  : "missing";
const attributedLines = fs.existsSync(attributedTsv)
  ? fs.readFileSync(attributedTsv, "utf8").trim().split(/\r?\n/).length - 1
  : "missing";

const reportLines = [
  `${book} proofread extraction report`,
  `generatedDate: ${generatedDate}`,
  `sourceDir: ${sourceDir}`,
  `sourceFilesForExport: ${files.length}`,
  `quoteCandidates: ${quoteCandidates}`,
  `uniqueQuoteTexts: ${uniqueQuoteTexts}`,
  `keywordLines: ${keywordLines}`,
  `reviewCandidates: ${reviewCandidateLines}`,
  `attributedLines: ${attributedLines}`,
  `initialSelectedRowsBeforeProofread: ${rawRows.length}`,
  `proofreadRemovedRows: ${proofreadRemovedRows.length}`,
  `proofreadAddedRows: ${proofreadAdditions.length}`,
  `selectedRows: ${selectedRows.length}`,
  `missingQuotes: ${missing.length}`,
  `duplicateTexts: ${duplicates.length}`,
  `politicalHitRows: ${politicalHits.length}`,
  "policy: this book is dominated by posthumous evaluation of Chiang Ching-kuo, Chiang family rule, KMT party-state materials, youth-army and cadre systems, Gannan administration, gold yuan currency cases, Taiwan politics and the Henry Liu/Jiang Nan case; exclude direct modern party, regime, leader, president, military, war, revolution, state, national-identity, diplomacy, constitutional, human-rights, ideological, assassination and succession quotations, while keeping independently reusable classical poetry/prose, ritual prose, idioms, proverbs, literary quotations, family-instruction phrases and non-political maxims.",
  "",
  "selectedHighlights:",
  "- 前言/001/002: 收《孟子》大丈夫句、志公与梁武帝文句、宋人题灵谷寺诗、陈后主诏句、崇祯史传文句、俗谚、汉武帝罪己诏与《淮南子》名句；蒋氏父子亡国、反攻和现代民主宪政攻防语录不收。",
  "- 003/004: 收读书格言、《孝经》名句、吴稚晖墓志文句、母子亲情散文句、孟郊诗句与三父八母民俗；蒋家身世和现代政治人物身份语境不收。",
  "- 007/009/011/012/015/016/019/023/025/026/028: 收通用成语、民谚、杜甫诗句、俗语和诗句化用；赣南统治、青年军、金圆券、接收贪污与权贵关系语录不收。",
  "- 029/032/033/035/036/037/039: 收官场成语、唐诗、圣经句、丧葬俗见、王充《论衡》、《礼记》、秦松龄诗、孔子语、闽南谚语、陆游诗句与《红楼梦》化句；总统继任、江南案、党国暗杀和民主自由政治语录不收。",
  "- 校对轮：增补扶不起的阿斗、与人为善、虚与委蛇、多如过江之鲫、鸣琴垂拱、一语成谶等可独立检索的成语俗语典故；移除蒋经国干部/用人演讲里的两条现代政治人物语录。",
  "",
  "excludedHighlights:",
  "- 前言/001/002: 追思经国、宽阔政治胸怀、复兴活在中国失败死在台湾、未来蒋家的人不能也不会担任总统、民主宪政、人权和自由政治评价均从严不收。",
  "- 006/007/009/010/014-018/021-024: 莫斯科革命表态、反共/青年军/三青团/中正学社/燕廉/铁血救国会等现代政治组织语录和口号不收。",
  "- 026/027/029/031/032/035/037/039: 金圆券、总统健康、李登辉继任、江南案、一清专案、国安法、政治冤狱和国府谋杀等现代政治法律语录不收；只留可独立检索的诗文、成语、俗语、典故和非政治格言。",
];

fs.writeFileSync(proofreadReportTxt, reportLines.join("\n") + "\n", "utf8");

console.log(
  JSON.stringify(
    {
      book,
      rows: selectedRows.length,
      missing: missing.length,
      duplicates: duplicates.length,
      politicalHitRows: politicalHits.length,
      quoteCandidates,
      uniqueQuoteTexts,
      keywordLines,
      reviewCandidates: reviewCandidateLines,
      attributedLines,
      outCsv,
      outTxt,
      selectedJson,
      initialReviewTsv: reviewTsv,
      initialAuditTsv: auditTsv,
      initialReportTxt: reportTxt,
      proofreadReviewTsv,
      proofreadAuditTsv,
      proofreadReportTxt,
    },
    null,
    2,
  ),
);
