const fs = require("fs");
const path = require("path");

const book = "李敖自传与回忆";
const rows = [
  {
    id: "LAZHYH-001",
    chapter: "001.李敖自传",
    source_file: "001.李敖自传.txt",
    line_start: 13,
    line_end: 13,
    quote_text: "盗不过五女之门",
    category: "俗语",
    source_or_origin: "汉代俗语（文中称“中国汉朝就有”）",
    summary: "李敖写母亲连生四女时，引此俗语说明旧时代重男轻女的社会压力。",
    notes: "",
  },
  {
    id: "LAZHYH-002",
    chapter: "001.李敖自传",
    source_file: "001.李敖自传.txt",
    line_start: 33,
    line_end: 33,
    quote_text: "你这位先生，妻不贤，子不孝。",
    category: "占语/警句",
    source_or_origin: "算命先生语",
    summary: "李敖记大爷算命一事，用这句带有俗世判断的占语写家庭关系的尴尬。",
    notes: "非公共典籍名句，因具格言式判断而收。",
  },
  {
    id: "LAZHYH-003",
    chapter: "001.李敖自传",
    source_file: "001.李敖自传.txt",
    line_start: 45,
    line_end: 45,
    quote_text: "七两为参，三两为宝",
    category: "地方俗语",
    source_or_origin: "东北土话",
    summary: "李敖说明吉林三宝中的人参，以东北土话强调大人参珍贵难得。",
    notes: "",
  },
  {
    id: "LAZHYH-004",
    chapter: "001.李敖自传",
    source_file: "001.李敖自传.txt",
    line_start: 73,
    line_end: 73,
    quote_text: "季子平安否",
    category: "词句",
    source_or_origin: "顾贞观《金缕曲》",
    summary: "李敖写“下关东”与发配东北时，引顾贞观词中吴汉槎典故，说明东北曾是流放地。",
    notes: "",
  },
  {
    id: "LAZHYH-005",
    chapter: "001.李敖自传",
    source_file: "001.李敖自传.txt",
    line_start: 93,
    line_end: 93,
    quote_text: "穷山恶水，丑妇刁民",
    category: "俗语/骂语",
    source_or_origin: "家族口头语",
    summary: "李敖记祖父骂祖母的话，用粗粝俗语呈现旧式家庭和地方偏见。",
    notes: "同句在《我最难忘的一位老师》回忆家世时又出现。",
  },
  {
    id: "LAZHYH-006",
    chapter: "001.李敖自传",
    source_file: "001.李敖自传.txt",
    line_start: 227,
    line_end: 227,
    quote_text: "去国八千里，谊兼师友，晨夕过从，方冀联骠归故里；订交三十年，情比弟昆，金兰契合，何期驾鹤脱凡尘。",
    category: "挽联",
    source_or_origin: "吴焕章、张松涵挽李鼎彝联",
    summary: "李敖写父亲与吴焕章等人的交情，以挽联概括离乱、师友情谊和生死之叹。",
    notes: "",
  },
  {
    id: "LAZHYH-007",
    chapter: "001.李敖自传",
    source_file: "001.李敖自传.txt",
    line_start: 437,
    line_end: 437,
    quote_text: "日卖百钱，以代耕稼，实救困贫，托名风雅。",
    category: "文人语",
    source_or_origin: "郑燮卖画自述",
    summary: "李敖介绍郑板桥生祠时，用郑燮卖画语表现其落拓而自嘲的文人气。",
    notes: "",
  },
  {
    id: "LAZHYH-008",
    chapter: "001.李敖自传",
    source_file: "001.李敖自传.txt",
    line_start: 437,
    line_end: 437,
    quote_text: "天荒食粥竟为常，惭对吾儿泪数行",
    category: "诗句",
    source_or_origin: "郑燮诗句（文中引）",
    summary: "李敖引郑板桥丧子前的贫困诗句，衬出郑燮早年的清贫与悲苦。",
    notes: "",
  },
  {
    id: "LAZHYH-009",
    chapter: "001.李敖自传",
    source_file: "001.李敖自传.txt",
    line_start: 437,
    line_end: 437,
    quote_text: "大幅四两，小幅二两，书条对联一两，扇子斗方五钱。凡送礼物食物，不如白银为妙，盖公之所赠，未必弟之所好也。若送现银，则心中喜乐，书画皆佳。礼物既属纠缠，赊欠尤恐赖帐，年老神倦，不能陪诸君子作无益语言也。",
    category: "润例/文人名言",
    source_or_origin: "郑燮自订润例",
    summary: "李敖引郑板桥卖画润例，凸显其坦率、风趣、现实而不失洒脱的性格。",
    notes: "",
  },
  {
    id: "LAZHYH-010",
    chapter: "001.李敖自传",
    source_file: "001.李敖自传.txt",
    line_start: 483,
    line_end: 483,
    quote_text: "唉！在我初次偷了那册课本带给你的时候，如果你痛打我一顿，那我也不会落到这样的地步了。",
    category: "寓言警句",
    source_or_origin: "《伊索寓言》故事（文中称原为咬耳，校长讲成咬奶头）",
    summary: "李敖记小学听校长讲故事，用寓言式结语说明纵容小恶会养成大恶。",
    notes: "",
  },
  {
    id: "LAZHYH-011",
    chapter: "001.李敖自传",
    source_file: "001.李敖自传.txt",
    line_start: 587,
    line_end: 597,
    quote_text: "你永远记得我们佟府吗？它便是我们的第二安乐家，静静的曲巷门前少人喧，深深的庭院丛树碧无涯。朝阳中朗朗诵破万卷书，笑语中尽是手足情欢洽。佟府胜过故乡，我们焉能忘？人生标的何处？凭你指方向……",
    category: "歌词",
    source_or_origin: "贝满女中部歌词，陈教务长作（文中称）",
    summary: "李敖转述姐姐回忆，用校歌式歌词呈现贝满女中的校园气氛和教育感情。",
    notes: "",
  },
  {
    id: "LAZHYH-012",
    chapter: "001.李敖自传",
    source_file: "001.李敖自传.txt",
    line_start: 611,
    line_end: 611,
    quote_text: "云鬟不整惊魂定",
    category: "诗句",
    source_or_origin: "吴伟业《圆圆曲》",
    summary: "李敖转述语文课讲陈圆圆故事时的课文句子，并由此引出课堂玩笑。",
    notes: "",
  },
  {
    id: "LAZHYH-013",
    chapter: "001.李敖自传",
    source_file: "001.李敖自传.txt",
    line_start: 649,
    line_end: 649,
    quote_text: "老渔翁，一钓竿，靠山崖，傍水湾，扁舟来往无牵绊。……",
    category: "曲词/道情",
    source_or_origin: "昆腔道情（文中称）",
    summary: "李敖转述母亲在家唱的道情，用曲词写母亲要钱逛街前的生活情景。",
    notes: "原曲出处待考。",
  },
  {
    id: "LAZHYH-014",
    chapter: "001.李敖自传",
    source_file: "001.李敖自传.txt",
    line_start: 711,
    line_end: 731,
    quote_text: "石榴开花满地红啊，二十的青年去从戎啊！第一杯茶呀，敬我的爹呀，我去当兵爹种田哪！第二杯茶呀，敬我的娘啊，我去当兵娘烧香啊！第三杯茶呀，敬我的哥啊，我去当兵没奈何啊！第四杯茶呀，敬我的嫂呀，我去当兵妯娌好啊！第五杯茶呀，敬我的妹呀，我去当兵陪嫂睡呀！第六杯茶呀，敬我的妻呀，我去当兵莫哭啼呀！爹娘说话你要听啊，大伯子说话莫插嘴啊！少上东家说闲话啊，少上西家串门子。少搽胭脂少抹粉，少上当街看秧歌。",
    category: "民歌/从戎歌",
    source_or_origin: "旧时从戎歌（文中称）",
    summary: "李敖转述兄弟姐妹小剧团常唱的从戎歌，保存家庭演出和民间歌谣记忆。",
    notes: "",
  },
  {
    id: "LAZHYH-015",
    chapter: "001.李敖自传",
    source_file: "001.李敖自传.txt",
    line_start: 741,
    line_end: 741,
    quote_text: "人不可一日无权，人不可一日无钱。",
    category: "现代格言",
    source_or_origin: "文革期间同事妙论（文中称）",
    summary: "李敖转述姐姐回忆，用一句现实主义格言说明权与钱在家庭权力结构中的作用。",
    notes: "",
  },
  {
    id: "LAZHYH-016",
    chapter: "001.李敖自传",
    source_file: "001.李敖自传.txt",
    line_start: 765,
    line_end: 765,
    quote_text: "保媒一百个，阎王爷给让座",
    category: "俗语",
    source_or_origin: "说媒俗语",
    summary: "李敖转述王墨林太太爱保媒，以俗语说明旧式婚姻撮合的功德观。",
    notes: "",
  },
  {
    id: "LAZHYH-017",
    chapter: "001.李敖自传",
    source_file: "001.李敖自传.txt",
    line_start: 809,
    line_end: 809,
    quote_text: "上天言好事，回宫降吉祥",
    category: "祭灶联语",
    source_or_origin: "民间祭灶用语",
    summary: "李敖写北京过年祭灶习俗，用灶王爷联语呈现民间信仰的交易性。",
    notes: "",
  },
  {
    id: "LAZHYH-018",
    chapter: "001.李敖自传",
    source_file: "001.李敖自传.txt",
    line_start: 845,
    line_end: 845,
    quote_text: "福无双至，祸不单行",
    category: "俗语",
    source_or_origin: "传统俗语",
    summary: "李敖转述姐姐幼年丧亲后的恐惧，用俗话概括坏事连番而来的心理感受。",
    notes: "",
  },
  {
    id: "LAZHYH-019",
    chapter: "001.李敖自传",
    source_file: "001.李敖自传.txt",
    line_start: 845,
    line_end: 845,
    quote_text: "运来推不开，倒霉一齐来",
    category: "俗语",
    source_or_origin: "上海俗语（文中称“上海人另有说法”）",
    summary: "李敖用上海俗语补充“祸不单行”的意思，写亲人死亡后的连锁阴影。",
    notes: "",
  },
  {
    id: "LAZHYH-020",
    chapter: "001.李敖自传",
    source_file: "001.李敖自传.txt",
    line_start: 913,
    line_end: 913,
    quote_text: "剃头挑子一头热",
    category: "北京土话",
    source_or_origin: "北京俗语",
    summary: "李敖转述亲戚恋爱往事，用北京土话形容单方面热恋。",
    notes: "",
  },
  {
    id: "LAZHYH-021",
    chapter: "002.从上海到海上",
    source_file: "002.从上海到海上.txt",
    line_start: 7,
    line_end: 7,
    quote_text: "兄弹弟腹穿，弟弹兄脑裂",
    category: "诗句",
    source_or_origin: "梁秋水《冀东兄弟行》",
    summary: "李敖写国共内战中兄弟相残，引梁秋水诗句强化内战惨烈。",
    notes: "",
  },
  {
    id: "LAZHYH-022",
    chapter: "002.从上海到海上",
    source_file: "002.从上海到海上.txt",
    line_start: 9,
    line_end: 9,
    quote_text: "根株浮沧海",
    category: "诗句",
    source_or_origin: "陶渊明诗句（文中称）",
    summary: "李敖坐船绕山东南下，借陶渊明诗句感叹家族迁徙努力归于漂浮。",
    notes: "",
  },
  {
    id: "LAZHYH-023",
    chapter: "002.从上海到海上",
    source_file: "002.从上海到海上.txt",
    line_start: 27,
    line_end: 27,
    quote_text: "目下一言为定，早晚市价不同",
    category: "时局俗语/招牌语",
    source_or_origin: "上海金圆券时期商店牌语",
    summary: "李敖写通货膨胀失控，用商店牌语说明物价连早晚都无法一致。",
    notes: "",
  },
  {
    id: "LAZHYH-024",
    chapter: "002.从上海到海上",
    source_file: "002.从上海到海上.txt",
    line_start: 33,
    line_end: 33,
    quote_text: "取之于民，用之于民，用作戡乱，以慰民望",
    category: "政治口号/套语",
    source_or_origin: "国民党政府搬运黄金时的说辞（文中称）",
    summary: "李敖批评国民党以大道理包装掠取民间黄金，用此句讽刺政治语言。",
    notes: "",
  },
  {
    id: "LAZHYH-025",
    chapter: "002.从上海到海上",
    source_file: "002.从上海到海上.txt",
    line_start: 39,
    line_end: 39,
    quote_text: "大头小头，叮叮当当",
    category: "市井俗语",
    source_or_origin: "上海银元流通时市面说法",
    summary: "李敖写金圆券失信后民间改用银元，用俗语描绘袁大头、孙小头叮当流通。",
    notes: "",
  },
  {
    id: "LAZHYH-026",
    chapter: "003.我最难忘的一位老师",
    source_file: "003.我最难忘的一位老师.txt",
    line_start: 23,
    line_end: 23,
    quote_text: "优胜劣败，适者生存",
    category: "现代格言/译语",
    source_or_origin: "严复《天演论》传播的进化论公式",
    summary: "李敖写严复思想进入近代中国，以此说明《天演论》刺激爱国青年。",
    notes: "",
  },
  {
    id: "LAZHYH-027",
    chapter: "003.我最难忘的一位老师",
    source_file: "003.我最难忘的一位老师.txt",
    line_start: 23,
    line_end: 23,
    quote_text: "物竞天择，适者生存",
    category: "现代格言/译语",
    source_or_origin: "严复《天演论》相关译语",
    summary: "李敖借胡适取字故事，说明严复译语如何成为近代中国人的命名和思想资源。",
    notes: "",
  },
  {
    id: "LAZHYH-028",
    chapter: "003.我最难忘的一位老师",
    source_file: "003.我最难忘的一位老师.txt",
    line_start: 26,
    line_end: 26,
    quote_text: "传家以孝，为国维忠",
    category: "家训/排行语",
    source_or_origin: "严复所立严氏家族排行语",
    summary: "李敖介绍严侨家世时，引严复家训说明严氏后代命名与忠孝观。",
    notes: "",
  },
  {
    id: "LAZHYH-029",
    chapter: "003.我最难忘的一位老师",
    source_file: "003.我最难忘的一位老师.txt",
    line_start: 38,
    line_end: 38,
    quote_text: "数学是人类智力的灵魂。……它超越了空间与时间的领域，告诉我们宇宙是这样的悠远，光线曾经历百万年的行程，方才照射到大地上。……",
    category: "外国名言",
    source_or_origin: "Oscar W. Anthony（文中称）",
    summary: "李敖回忆自己在数学练习簿中引用此语，表现少年时爱把课堂作业变成思想辩论。",
    notes: "",
  },
  {
    id: "LAZHYH-030",
    chapter: "003.我最难忘的一位老师",
    source_file: "003.我最难忘的一位老师.txt",
    line_start: 62,
    line_end: 78,
    quote_text: "醉里且贪欢笑，要愁那得工夫？近来始觉古人书，信着全无是处。昨夜松边醉倒，问松：“我醉何如？”只疑松动要来扶，以手推松曰：“去！”",
    category: "词",
    source_or_origin: "辛弃疾《西江月·遣兴》",
    summary: "李敖写严侨酒后常背此词，借“以手推松”表现严侨醉中豪气和悲剧性真情。",
    notes: "",
  },
  {
    id: "LAZHYH-031",
    chapter: "003.我最难忘的一位老师",
    source_file: "003.我最难忘的一位老师.txt",
    line_start: 120,
    line_end: 124,
    quote_text: "委蜕大难求净土，伤心最是近高楼！",
    category: "诗句",
    source_or_origin: "陈宝琛诗句（文中称）",
    summary: "李敖写自己在台大“四席小屋”的孤寂处境，以陈宝琛诗句表达乱世求净土之难。",
    notes: "同一引用在本书多篇中重复出现。",
  },
  {
    id: "LAZHYH-032",
    chapter: "003.我最难忘的一位老师",
    source_file: "003.我最难忘的一位老师.txt",
    line_start: 188,
    line_end: 190,
    quote_text: "横眉冷对千夫指，俯首甘为孺子牛。",
    category: "诗句",
    source_or_origin: "鲁迅《自嘲》",
    summary: "李敖写重见严侨时，严侨借鲁迅诗句说明自己出狱后的转变：放下“横眉”，转向照顾孩子。",
    notes: "",
  },
  {
    id: "LAZHYH-033",
    chapter: "005.“北土非吾愿，东林怀我师”",
    source_file: "005.“北土非吾愿，东林怀我师”.txt",
    line_start: 1,
    line_end: 1,
    quote_text: "北土非吾愿，东林怀我师",
    category: "诗句/题名",
    source_or_origin: "孟浩然《秦中感秋寄远上人》",
    summary: "李敖以此作篇名，借思师诗意总括他回想姚从吾老师的师生之情。",
    notes: "",
  },
  {
    id: "LAZHYH-034",
    chapter: "005.“北土非吾愿，东林怀我师”",
    source_file: "005.“北土非吾愿，东林怀我师”.txt",
    line_start: 201,
    line_end: 201,
    quote_text: "吃饭八成饱，觉睡十分好；按部就班去，听其自然老。书读万卷勤，文写百篇精；循规蹈矩来，看你平安归。",
    category: "五言诗/挽联",
    source_or_origin: "姚从吾养生诗与方豪续成挽联（文中称）",
    summary: "李敖引姚从吾通俗养生诗及方豪续联，呈现姚从吾朴素保守的生活气质。",
    notes: "",
  },
  {
    id: "LAZHYH-035",
    chapter: "005.“北土非吾愿，东林怀我师”",
    source_file: "005.“北土非吾愿，东林怀我师”.txt",
    line_start: 211,
    line_end: 213,
    quote_text: "委蜕大难求净土，伤心最是近高楼！",
    category: "诗句",
    source_or_origin: "陈宝琛诗句（文中称）",
    summary: "李敖在《十三年和十三月》引此句，写退伍返台大后身处小屋的孤独与时代压迫感。",
    notes: "重复引用。",
  },
  {
    id: "LAZHYH-036",
    chapter: "005.“北土非吾愿，东林怀我师”",
    source_file: "005.“北土非吾愿，东林怀我师”.txt",
    line_start: 233,
    line_end: 233,
    quote_text: "教育好象是一架冷冻机，接近它的时间愈久，人就变成愈冷淡。太多的理智恰像泰格尔形容的无柄刀子，也许很实际很有用，可是太不可爱了！",
    category: "现代名言/外国典故",
    source_or_origin: "李敖语，含泰戈尔“无柄刀子”比喻",
    summary: "李敖批评学院教育把人变冷，把过度理智比作泰戈尔式无柄刀子。",
    notes: "文中作“泰格尔”。",
  },
  {
    id: "LAZHYH-037",
    chapter: "005.“北土非吾愿，东林怀我师”",
    source_file: "005.“北土非吾愿，东林怀我师”.txt",
    line_start: 237,
    line_end: 237,
    quote_text: "白首下书帷",
    category: "古典成句/读书意象",
    source_or_origin: "古典诗文成句，出处未核",
    summary: "李敖用此句概括姚从吾式白首校书的学院道路，并说明自己当时还不愿过早进入这种生活。",
    notes: "保留为典故性短语。",
  },
  {
    id: "LAZHYH-038",
    chapter: "005.“北土非吾愿，东林怀我师”",
    source_file: "005.“北土非吾愿，东林怀我师”.txt",
    line_start: 269,
    line_end: 269,
    quote_text: "不受三年苦，难得人上人。",
    category: "俗语/劝勉语",
    source_or_origin: "姚从吾信中劝语",
    summary: "姚从吾劝李敖志向放大、忍受困难，李敖引此表现老师对他的期待。",
    notes: "",
  },
  {
    id: "LAZHYH-039",
    chapter: "005.“北土非吾愿，东林怀我师”",
    source_file: "005.“北土非吾愿，东林怀我师”.txt",
    line_start: 331,
    line_end: 333,
    quote_text: "委蜕大难求净土，伤心最是近高楼！",
    category: "诗句",
    source_or_origin: "陈宝琛诗句（文中称）",
    summary: "李敖写给姚从吾信中再引此句，以“高楼”“净土”比喻受姚支持后的暂时安身。",
    notes: "重复引用。",
  },
  {
    id: "LAZHYH-040",
    chapter: "005.“北土非吾愿，东林怀我师”",
    source_file: "005.“北土非吾愿，东林怀我师”.txt",
    line_start: 357,
    line_end: 357,
    quote_text: "行有余力，则以学文",
    category: "儒家名句",
    source_or_origin: "《论语·学而》",
    summary: "李敖讨论穷困影响治学时，强调“余力”的前提是先能活得下去。",
    notes: "",
  },
  {
    id: "LAZHYH-041",
    chapter: "005.“北土非吾愿，东林怀我师”",
    source_file: "005.“北土非吾愿，东林怀我师”.txt",
    line_start: 371,
    line_end: 371,
    quote_text: "日得百钱，则甘旨足矣",
    category: "古文名句",
    source_or_origin: "《东轩笔录》故事（文中称）",
    summary: "李敖引孙明复故事，说明贫困会迫使有才者奔走求食。",
    notes: "",
  },
  {
    id: "LAZHYH-042",
    chapter: "005.“北土非吾愿，东林怀我师”",
    source_file: "005.“北土非吾愿，东林怀我师”.txt",
    line_start: 371,
    line_end: 371,
    quote_text: "贫之为累大矣，倘索米至老，则才如明复，犹将汨没而不见也！",
    category: "古文名句",
    source_or_origin: "范仲淹语（《东轩笔录》故事，文中称）",
    summary: "李敖借范仲淹感叹说明贫穷对学问与人才的压迫。",
    notes: "",
  },
  {
    id: "LAZHYH-043",
    chapter: "005.“北土非吾愿，东林怀我师”",
    source_file: "005.“北土非吾愿，东林怀我师”.txt",
    line_start: 381,
    line_end: 381,
    quote_text: "行有余力，则以跑野马",
    category: "仿拟名句",
    source_or_origin: "李敖仿《论语》语",
    summary: "李敖戏仿“行有余力，则以学文”，感谢姚从吾包容他的懒惰、立异和自由活动。",
    notes: "",
  },
  {
    id: "LAZHYH-044",
    chapter: "005.“北土非吾愿，东林怀我师”",
    source_file: "005.“北土非吾愿，东林怀我师”.txt",
    line_start: 397,
    line_end: 397,
    quote_text: "失之东隅，收之桑榆",
    category: "成语",
    source_or_origin: "传统成语",
    summary: "李敖写考研究所后以为可转任助教，用成语表达损失中另有补偿的盘算。",
    notes: "",
  },
  {
    id: "LAZHYH-045",
    chapter: "005.“北土非吾愿，东林怀我师”",
    source_file: "005.“北土非吾愿，东林怀我师”.txt",
    line_start: 493,
    line_end: 493,
    quote_text: "不入虎穴，焉得虎子",
    category: "成语",
    source_or_origin: "传统成语",
    summary: "吴相湘劝李敖进文献会看史料，李敖以此记录老师们劝他接近陶希圣阵营的理由。",
    notes: "",
  },
  {
    id: "LAZHYH-046",
    chapter: "005.“北土非吾愿，东林怀我师”",
    source_file: "005.“北土非吾愿，东林怀我师”.txt",
    line_start: 611,
    line_end: 611,
    quote_text: "此度见花枝，白发誓不归",
    category: "诗句",
    source_or_origin: "诗句，出处未核",
    summary: "李敖离开文献会时为向泽洲题字，用此句表达不回头、不归附的决绝姿态。",
    notes: "",
  },
  {
    id: "LAZHYH-047",
    chapter: "005.“北土非吾愿，东林怀我师”",
    source_file: "005.“北土非吾愿，东林怀我师”.txt",
    line_start: 817,
    line_end: 823,
    quote_text: "道狭草木长，夕露沾我衣。衣沾不足惜，但使愿无违！",
    category: "诗句",
    source_or_origin: "陶渊明《归园田居》",
    summary: "李敖以陶渊明“不合作”诗意总结自己拒绝国民党合作、坚持做自己的代价。",
    notes: "",
  },
  {
    id: "LAZHYH-048",
    chapter: "006.提升文星的一个回忆",
    source_file: "006.提升文星的一个回忆.txt",
    line_start: 5,
    line_end: 5,
    quote_text: "行有余力则以学文",
    category: "儒家名句",
    source_or_origin: "《论语·学而》",
    summary: "李敖谈萧孟能经营《文星》与文化事业，借此说明经济余力对思想文化传播的重要。",
    notes: "此处原文未加逗号。",
  },
  {
    id: "LAZHYH-049",
    chapter: "007.我最难忘的一个警察",
    source_file: "007.我最难忘的一个警察.txt",
    line_start: 5,
    line_end: 5,
    quote_text: "福无双至，祸不单行。",
    category: "俗语",
    source_or_origin: "传统俗语",
    summary: "李敖写被跟监期间的自我修炼，先解释俗话中“祸”的心理连锁。",
    notes: "同句在《李敖自传》中也出现。",
  },
  {
    id: "LAZHYH-050",
    chapter: "007.我最难忘的一个警察",
    source_file: "007.我最难忘的一个警察.txt",
    line_start: 5,
    line_end: 5,
    quote_text: "善因祸而为福，转败而为功",
    category: "史传名句",
    source_or_origin: "司马迁《史记·管晏列传》评管仲语（文中称）",
    summary: "李敖把此句当成被软禁时的处世本领：把国民党的监控转化为对自己有利。",
    notes: "",
  },
  {
    id: "LAZHYH-051",
    chapter: "007.我最难忘的一个警察",
    source_file: "007.我最难忘的一个警察.txt",
    line_start: 5,
    line_end: 5,
    quote_text: "人生不如意事，常十之八九。",
    category: "俗语",
    source_or_origin: "传统俗语",
    summary: "李敖用此俗语说明多数不顺之事可经由高手转化为有利条件。",
    notes: "",
  },
  {
    id: "LAZHYH-052",
    chapter: "009.我最难忘的一个“匪谍”",
    source_file: "009.我最难忘的一个“匪谍”.txt",
    line_start: 87,
    line_end: 87,
    quote_text: "说谎的人需有好的记忆力",
    category: "西谚",
    source_or_origin: "西方谚语（文中称“西谚”）",
    summary: "李敖为黄中国案写辩护材料时，用西谚攻击证人前后矛盾、记忆不可靠。",
    notes: "",
  },
  {
    id: "LAZHYH-053",
    chapter: "009.我最难忘的一个“匪谍”",
    source_file: "009.我最难忘的一个“匪谍”.txt",
    line_start: 241,
    line_end: 241,
    quote_text: "一饮一啄，莫非前定",
    category: "俗语/佛道宿命语",
    source_or_origin: "传统俗语",
    summary: "李敖分吃黄中国遗留水果时，用此语写死囚遗物阴错阳差落入他人腹中的宿命感。",
    notes: "",
  },
  {
    id: "LAZHYH-054",
    chapter: "009.我最难忘的一个“匪谍”",
    source_file: "009.我最难忘的一个“匪谍”.txt",
    line_start: 247,
    line_end: 247,
    quote_text: "出于尘土、归于尘土",
    category: "宗教典故",
    source_or_origin: "《圣经》“dust to dust”意象",
    summary: "李敖写黄中国被时代吞没后的消失，用圣经式语句概括一名政治牺牲者的归宿。",
    notes: "原文未加引号。",
  },
  {
    id: "LAZHYH-055",
    chapter: "010.我最难忘的一个小偷",
    source_file: "010.我最难忘的一个小偷.txt",
    line_start: 19,
    line_end: 19,
    quote_text: "牢房一别后，流水十年间。",
    category: "仿拟诗句",
    source_or_origin: "仿韦应物“浮云一别后，流水十年间”",
    summary: "李敖写与狱中小偷十年不见，化用古诗句制造诙谐而沧桑的回忆开头。",
    notes: "",
  },
  {
    id: "LAZHYH-056",
    chapter: "012.我最难忘的一个流氓",
    source_file: "012.我最难忘的一个流氓.txt",
    line_start: 21,
    line_end: 21,
    quote_text: "千万别同警察交朋友，因为你不晓得他什么时候‘公事公办。’",
    category: "外国谚语",
    source_or_origin: "美国黑社会谚语（文中称）",
    summary: "李敖借美国黑社会谚语说明警察随时会翻脸，以此谈流氓和警察的关系。",
    notes: "",
  },
  {
    id: "LAZHYH-057",
    chapter: "013.我最难忘的一段洗脑",
    source_file: "013.我最难忘的一段洗脑.txt",
    line_start: 53,
    line_end: 53,
    quote_text: "吾日三省吾身。",
    category: "儒家名句",
    source_or_origin: "《论语·学而》",
    summary: "李敖写国民党“反省院”制度，借曾子语指出“反省”一词被机关化、政治化。",
    notes: "",
  },
  {
    id: "LAZHYH-058",
    chapter: "013.我最难忘的一段洗脑",
    source_file: "013.我最难忘的一段洗脑.txt",
    line_start: 61,
    line_end: 61,
    quote_text: "传不习乎？",
    category: "儒家名句",
    source_or_origin: "《论语·学而》",
    summary: "黄宝实自述读书时引用曾子第三省，李敖转述以说明反省院主持者的自我修养说法。",
    notes: "",
  },
  {
    id: "LAZHYH-059",
    chapter: "013.我最难忘的一段洗脑",
    source_file: "013.我最难忘的一段洗脑.txt",
    line_start: 61,
    line_end: 61,
    quote_text: "一行作吏，此心全非",
    category: "仕隐训语",
    source_or_origin: "传统训语，出处未核",
    summary: "黄宝实说自己受此训诫影响而不愿作俗吏，李敖转述以呈现旧文人的自我标榜。",
    notes: "",
  },
  {
    id: "LAZHYH-060",
    chapter: "013.我最难忘的一段洗脑",
    source_file: "013.我最难忘的一段洗脑.txt",
    line_start: 61,
    line_end: 61,
    quote_text: "古之学者为己",
    category: "儒家名句",
    source_or_origin: "《论语·宪问》",
    summary: "黄宝实以此说明读书为自我修养而非外在督责，李敖转述后再批评反省教育的实效。",
    notes: "",
  },
  {
    id: "LAZHYH-061",
    chapter: "014.被封杀的“人民公敌”",
    source_file: "014.被封杀的“人民公敌”.txt",
    line_start: 23,
    line_end: 23,
    quote_text: "教育好像是一架冷冻机，接近它的时间愈久，人就变成愈冷淡。太多的理智恰像泰戈尔形容的无柄刀子，也许很实际很有用，可是太不可爱了！",
    category: "现代名言/外国典故",
    source_or_origin: "李敖语，含泰戈尔“无柄刀子”比喻",
    summary: "李敖在自述大学经验时再引此语，批评高等教育冷化人性。",
    notes: "与005篇中同段重复，字形作“泰戈尔”。",
  },
  {
    id: "LAZHYH-062",
    chapter: "014.被封杀的“人民公敌”",
    source_file: "014.被封杀的“人民公敌”.txt",
    line_start: 29,
    line_end: 33,
    quote_text: "委蛻大难求净土，伤心最是近高楼！",
    category: "诗句",
    source_or_origin: "陈宝琛诗句（文中称）",
    summary: "李敖在被封杀叙事中重提退伍返台大的孤寂，用此句贯穿早年精神处境。",
    notes: "重复引用。",
  },
  {
    id: "LAZHYH-063",
    chapter: "014.被封杀的“人民公敌”",
    source_file: "014.被封杀的“人民公敌”.txt",
    line_start: 139,
    line_end: 145,
    quote_text: "你已经吞了不少苦药。请再勇敢的喝了这杯毒酒吧！",
    category: "外国诗句/改译",
    source_or_origin: "印度古伽拉德青年诗人（文中称“两句改译”）",
    summary: "李敖写文坛争战中的自我鼓励，以改译诗句把苦难升级为主动承受的毒酒。",
    notes: "原作者与原文待考。",
  },
  {
    id: "LAZHYH-064",
    chapter: "014.被封杀的“人民公敌”",
    source_file: "014.被封杀的“人民公敌”.txt",
    line_start: 147,
    line_end: 189,
    quote_text: "我们相信：他们只是一种气候，像一阵阴天，他们总要过去。我们相信：他们只是一股逆流，在阳光下与大河旁，没有他们的余地。从任何因素判断，他们没有理由长久，他们的存在，早不是天理，而是运气。我们相信：我们会等待到那一天，我们会制造出那一天。而我们，不该是阴天的烈士，或是逆流的殉葬者。我们不单是为唾弃他们而生，我们有我们要做的事。",
    category: "现代诗",
    source_or_origin: "李敖《我们相信》（1967年小诗，文中称）",
    summary: "李敖用自己的小诗总结被封杀后的信念：压迫只是阴天与逆流，自己不只为反抗而生。",
    notes: "",
  },
  {
    id: "LAZHYH-065",
    chapter: "001.李敖自传",
    source_file: "001.李敖自传.txt",
    line_start: 433,
    line_end: 433,
    quote_text: "佞词累牍，不顾羞耻。",
    category: "史传评语",
    source_or_origin: "《明史·魏忠贤传》（文中称）",
    summary: "李敖写魏忠贤生祠时，引史传评语概括群臣争写颂词、拍附权阉的丑态。",
    notes: "校对轮补入。",
  },
  {
    id: "LAZHYH-066",
    chapter: "001.李敖自传",
    source_file: "001.李敖自传.txt",
    line_start: 461,
    line_end: 461,
    quote_text: "飞飞飞蝶飞飞飞，飞到鸳鸯天芳草地，飞飞飞蝶飞飞飞",
    category: "儿歌/歌词",
    source_or_origin: "歌曲《飞》（文中称）",
    summary: "李敖回忆小学音乐课，以第一首学歌呈现童年学校生活的声音记忆。",
    notes: "校对轮补入。",
  },
  {
    id: "LAZHYH-067",
    chapter: "001.李敖自传",
    source_file: "001.李敖自传.txt",
    line_start: 463,
    line_end: 469,
    quote_text: "好大的西北风啊，飞到一座树林里。它叫树林跳舞啊，一二三四呼呼呼。它对树林大声说：现在已经不早了，大家都要用些劲儿，一二三四呼呼呼。",
    category: "歌词",
    source_or_origin: "刘复、赵元任《好大的西北风》（文中称）",
    summary: "李敖记小学音乐课唱《好大的西北风》，借歌词和寒冬教室构成童年北京的感官记忆。",
    notes: "校对轮补入。",
  },
  {
    id: "LAZHYH-068",
    chapter: "001.李敖自传",
    source_file: "001.李敖自传.txt",
    line_start: 599,
    line_end: 599,
    quote_text: "女人要能独立工作，不靠丈夫吃饭",
    category: "家庭训语/现代格言",
    source_or_origin: "李敖母亲灌输的家庭理想",
    summary: "李敖写母亲规划女儿教育时，引此家庭训语说明母亲重视女性经济独立的观念。",
    notes: "校对轮补入；非典籍名句，因具明确训语性质而收。",
  },
  {
    id: "LAZHYH-069",
    chapter: "003.我最难忘的一位老师",
    source_file: "003.我最难忘的一位老师.txt",
    line_start: 242,
    line_end: 242,
    quote_text: "害之反足以成之",
    category: "文言成句",
    source_or_origin: "成语式文言成句，出处待考",
    summary: "李敖评论敌手公布其信反而促成传播，用此成句概括迫害意图转成反效果。",
    notes: "校对轮补入。",
  },
  {
    id: "LAZHYH-070",
    chapter: "003.我最难忘的一位老师",
    source_file: "003.我最难忘的一位老师.txt",
    line_start: 258,
    line_end: 258,
    quote_text: "欲盖弥彰",
    category: "成语",
    source_or_origin: "成语",
    summary: "李敖转述胡秋原读后感中对信件身份问题的指控，保留对方以成语作推断的说法。",
    notes: "校对轮补入；引语来自胡秋原文字。",
  },
  {
    id: "LAZHYH-071",
    chapter: "003.我最难忘的一位老师",
    source_file: "003.我最难忘的一位老师.txt",
    line_start: 258,
    line_end: 258,
    quote_text: "此地无银三百两",
    category: "俗语/成语",
    source_or_origin: "民间俗语",
    summary: "李敖转述胡秋原以俗语指称信中身份表述反显可疑，呈现当时政治攻讦的语言方式。",
    notes: "校对轮补入；引语来自胡秋原文字。",
  },
  {
    id: "LAZHYH-072",
    chapter: "003.我最难忘的一位老师",
    source_file: "003.我最难忘的一位老师.txt",
    line_start: 408,
    line_end: 408,
    quote_text: "若以色见我，以音声求我，是人行邪道，不能见如来。",
    category: "佛经偈句",
    source_or_origin: "《金刚经》",
    summary: "李敖批评严侨晚年所信佛教流于偶像崇拜，引《金刚经》说明真正佛教不应执着形相音声。",
    notes: "校对轮补入。",
  },
  {
    id: "LAZHYH-073",
    chapter: "003.我最难忘的一位老师",
    source_file: "003.我最难忘的一位老师.txt",
    line_start: 430,
    line_end: 430,
    quote_text: "若彼云雾，如见珠玉。宅相之寄，良在此甥。",
    category: "史传名句",
    source_or_origin: "《北齐书·李浑传》（文中称）",
    summary: "李敖解释严侨灵堂挽额“怆怀宅相”的典故，引《北齐书》说明“宅相”原为称美外甥之语。",
    notes: "校对轮补入。",
  },
  {
    id: "LAZHYH-074",
    chapter: "003.我最难忘的一位老师",
    source_file: "003.我最难忘的一位老师.txt",
    line_start: 494,
    line_end: 494,
    quote_text: "不到最后毁灭关头绝不轻言屈服",
    category: "现代政治格言",
    source_or_origin: "蒋介石语（文中称“套一句蒋总统的话”）",
    summary: "李敖写自己在权威压力下的韧性，用蒋介石式口号反讽地表达不妥协姿态。",
    notes: "校对轮补入。",
  },
  {
    id: "LAZHYH-075",
    chapter: "005.“北土非吾愿，东林怀我师”",
    source_file: "005.“北土非吾愿，东林怀我师”.txt",
    line_start: 101,
    line_end: 101,
    quote_text: "好话说三遍",
    category: "俗语",
    source_or_origin: "民间俗语",
    summary: "李敖评胡适反复称赞的态度，用俗语写自己对客套式好话的不耐。",
    notes: "校对轮补入。",
  },
  {
    id: "LAZHYH-076",
    chapter: "005.“北土非吾愿，东林怀我师”",
    source_file: "005.“北土非吾愿，东林怀我师”.txt",
    line_start: 801,
    line_end: 801,
    quote_text: "富贵如可求，虽执鞭之士，吾亦为之；如不可求，从吾所好。",
    category: "儒家名句",
    source_or_origin: "《论语·述而》",
    summary: "李敖解释姚从吾印章“从吾所好”的来历，并借《论语》转写姚、李之间由治学到师生情的关系。",
    notes: "校对轮补入。",
  },
  {
    id: "LAZHYH-077",
    chapter: "005.“北土非吾愿，东林怀我师”",
    source_file: "005.“北土非吾愿，东林怀我师”.txt",
    line_start: 801,
    line_end: 801,
    quote_text: "霸才无主始怜君",
    category: "诗句/出处待考",
    source_or_origin: "出处待考（文中作为诗句式短语引用）",
    summary: "李敖借此句揣测姚从吾怜爱其才的心理，把师生情写成才气相感的投射。",
    notes: "校对轮补入；暂未核定原始出处。",
  },
  {
    id: "LAZHYH-078",
    chapter: "001.李敖自传",
    source_file: "001.李敖自传.txt",
    line_start: 375,
    line_end: 375,
    quote_text: "人心者，国家之命脉也",
    category: "明代格言",
    source_or_origin: "吕坤《呻吟语》（文中称）",
    summary: "李敖写沈二爷只读《呻吟语》，引吕坤此语说明传统仕绅把人心视为国家根本。",
    notes: "校对轮补入。",
  },
  {
    id: "LAZHYH-079",
    chapter: "001.李敖自传",
    source_file: "001.李敖自传.txt",
    line_start: 541,
    line_end: 541,
    quote_text: "布谷声声，田里水飘飘……",
    category: "歌句",
    source_or_origin: "儿时歌曲片段，歌名待考",
    summary: "李敖回忆四妹童年时，以她常唱的歌句保存家庭记忆中少有的温柔片段。",
    notes: "校对轮补入；仅见残句。",
  },
  {
    id: "LAZHYH-080",
    chapter: "003.我最难忘的一位老师",
    source_file: "003.我最难忘的一位老师.txt",
    line_start: 406,
    line_end: 406,
    quote_text: "无所住而生其心",
    category: "佛经名句",
    source_or_origin: "《金刚经》",
    summary: "李敖引严琥信中对《金刚经》的理解，用此句说明不被固定成见拘束才是佛教智慧。",
    notes: "校对轮补入。",
  },
  {
    id: "LAZHYH-081",
    chapter: "013.我最难忘的一段洗脑",
    source_file: "013.我最难忘的一段洗脑.txt",
    line_start: 5,
    line_end: 5,
    quote_text: "人之患，在好为人师。",
    category: "儒家名句",
    source_or_origin: "《孟子·离娄上》",
    summary: "李敖以孟子这句开篇，转入对国民党反省教育中“教训人”心态的批判。",
    notes: "校对轮补入。",
  },
  {
    id: "LAZHYH-082",
    chapter: "013.我最难忘的一段洗脑",
    source_file: "013.我最难忘的一段洗脑.txt",
    line_start: 5,
    line_end: 5,
    quote_text: "好为人师，则自足而不复有进矣，此人之大患也！",
    category: "儒家注语",
    source_or_origin: "朱熹引王勉语（文中称）",
    summary: "李敖转述朱熹所引王勉解释，再反驳其解释不足，以凸显“好为人师”的优越感病态。",
    notes: "校对轮补入。",
  },
  {
    id: "LAZHYH-083",
    chapter: "001.李敖自传",
    source_file: "001.李敖自传.txt",
    line_start: 53,
    line_end: 53,
    quote_text: "我们不能盲从",
    category: "现代箴言",
    source_or_origin: "魏建功语（文中称）",
    summary: "李敖转述父亲所讲北大见闻，以魏建功反对盲目追捧爱罗先珂的话表现五四后北大的独立判断气氛。",
    notes: "校对轮补入。",
  },
  {
    id: "LAZHYH-084",
    chapter: "001.李敖自传",
    source_file: "001.李敖自传.txt",
    line_start: 375,
    line_end: 375,
    quote_text: "三十年来，所志呻吟语，凡若干卷，携以自药",
    category: "明代文人自述",
    source_or_origin: "吕坤《呻吟语》（文中称）",
    summary: "李敖说明《呻吟语》成书缘起时，引吕坤自述，把此书写成以文字自我治疗的修养札记。",
    notes: "校对轮补入。",
  },
  {
    id: "LAZHYH-085",
    chapter: "003.我最难忘的一位老师",
    source_file: "003.我最难忘的一位老师.txt",
    line_start: 430,
    line_end: 430,
    quote_text: "怆怀宅相",
    category: "挽额/典故",
    source_or_origin: "林柏寿横挽，典出“宅相”故事（文中引《北齐书·李浑传》解释）",
    summary: "李敖写严侨灵堂挽额，以“宅相”典故反衬严侨一生竟被姻亲身份框住的荒谬感。",
    notes: "校对轮补入。",
  },
];

const outDir = path.join(process.cwd(), "exports");
fs.mkdirSync(outDir, { recursive: true });

const columns = [
  "id",
  "book",
  "chapter",
  "source_file",
  "line_start",
  "line_end",
  "quote_text",
  "category",
  "source_or_origin",
  "summary",
  "notes",
];

const excludedSelfAuthoredIds = new Set([
  "LAZHYH-036",
  "LAZHYH-043",
  "LAZHYH-061",
  "LAZHYH-064",
]);

const outputRows = rows
  .filter((record) => !excludedSelfAuthoredIds.has(record.id))
  .sort(
  (a, b) =>
    a.source_file.localeCompare(b.source_file, "zh-Hans-CN") ||
    Number(a.line_start) - Number(b.line_start) ||
    a.id.localeCompare(b.id),
);

const csvEscape = (value) => {
  const text = value == null ? "" : String(value);
  return /[",\r\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
};

const csvLines = [
  columns.join(","),
  ...outputRows.map((row) =>
    columns
      .map((column) => csvEscape(column === "book" ? book : row[column]))
      .join(","),
  ),
];

const csvPath = path.join(outDir, "李敖自传与回忆_诗词名言引用.csv");
fs.writeFileSync(csvPath, `\uFEFF${csvLines.join("\r\n")}\r\n`, "utf8");

const txt = [];
txt.push(`《${book}》诗词名言引用摘录`);
txt.push(`生成日期：2026-06-15`);
txt.push("");
txt.push(
  "收录口径：诗词、联语、家训、谚语、格言、成语式历史名句、歌谣歌词，以及李敖明确用作论述或自我说明的典故性短语；纯对白、公文法规、机构名、普通书名篇名未列入。",
);
txt.push(`总计：${outputRows.length} 条。`);
txt.push("");

let currentChapter = "";
for (const row of outputRows) {
  if (row.chapter !== currentChapter) {
    currentChapter = row.chapter;
    txt.push(`## ${currentChapter}`);
  }
  txt.push(`${row.id}｜${row.category}｜${row.source_file}:${row.line_start}-${row.line_end}`);
  txt.push(`引用：${row.quote_text}`);
  txt.push(`出处线索：${row.source_or_origin}`);
  txt.push(`摘要：${row.summary}`);
  if (row.notes) txt.push(`备注：${row.notes}`);
  txt.push("");
}

const txtPath = path.join(outDir, "李敖自传与回忆_诗词名言引用.txt");
fs.writeFileSync(txtPath, `\uFEFF${txt.join("\r\n")}\r\n`, "utf8");

console.log(
  JSON.stringify(
    {
      rows: outputRows.length,
      excludedSelfAuthoredRows: rows.length - outputRows.length,
      csvPath,
      txtPath,
    },
    null,
    2,
  ),
);
